nameOverride: ""
fullnameOverride: ""
replicaCount: 3

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

debug: false
# Leave empty for stdout only
logsPath: ""

auth:
  saltCost: 10

  accessTokenSecrets:
    name: access-token-secrets
    signingKeyKey: signingKey

  accessTokenTtl: 20m
  refreshTokenTtl: 720h
  resetPasswordCodeTtl: 24h

  firebaseSecrets:
    name: firebase-secrets
    credentialsKey: credentials
    googleApiKey: googleApiKey

oauth:
  googleClientId: ""
  vkClientId: ""
  secrets:
    name: oauth-secrets
    googleClientSecretKey: googleClientSecret
    vkClientSecretKey: vkClientSecret

postgres:
  host: ""
  port: 5432
  secrets:
    name: postgres-secrets
    userKey: user
    passwordKey: password
  dbName: chefbook-auth

smtp:
  host: smtp.gmail.com
  port: 465
  email: ""
  secrets:
    name: smtp-secrets
    passwordKey: password
  sendAttempts: 3

secrets:
  dependencyEnabled: true

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
