apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chefbook-backend-auth-service.fullname" . }}-migrations-job
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chefbook-backend-auth-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chefbook-backend-auth-service.name" . }}-migration
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-migrations
          image: "{{ .Values.image.repository }}-migrations:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.postgres.host }}
            - name: DB_PORT
              value: {{ quote .Values.postgres.port }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secrets.name }}
                  key: {{ .Values.postgres.secrets.userKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secrets.name }}
                  key: {{ .Values.postgres.secrets.passwordKey }}
            - name: DB_NAME
              value: {{ .Values.postgres.dbName | quote }}
