// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/account-workflows.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reauthentication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IdToken       string                 `protobuf:"bytes,3,opt,name=idToken,proto3" json:"idToken,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reauthentication) Reset() {
	*x = Reauthentication{}
	mi := &file_v1_account_workflows_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reauthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reauthentication) ProtoMessage() {}

func (x *Reauthentication) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_workflows_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reauthentication.ProtoReflect.Descriptor instead.
func (*Reauthentication) Descriptor() ([]byte, []int) {
	return file_v1_account_workflows_proto_rawDescGZIP(), []int{0}
}

func (x *Reauthentication) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Reauthentication) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Reauthentication) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *Reauthentication) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Reauthentication) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type UpdateProfileDeletionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FlowBinding      string                 `protobuf:"bytes,20,opt,name=flowBinding,proto3" json:"flowBinding,omitempty"`
	UserId           string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DeleteSharedData bool                   `protobuf:"varint,2,opt,name=deleteSharedData,proto3" json:"deleteSharedData,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateProfileDeletionRequest) Reset() {
	*x = UpdateProfileDeletionRequest{}
	mi := &file_v1_account_workflows_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileDeletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileDeletionRequest) ProtoMessage() {}

func (x *UpdateProfileDeletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_workflows_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileDeletionRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileDeletionRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_workflows_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProfileDeletionRequest) GetFlowBinding() string {
	if x != nil {
		return x.FlowBinding
	}
	return ""
}

func (x *UpdateProfileDeletionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileDeletionRequest) GetDeleteSharedData() bool {
	if x != nil {
		return x.DeleteSharedData
	}
	return false
}

type UpdateProfileDeletionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeletionTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deletionTimestamp,proto3" json:"deletionTimestamp,omitempty"`
	DeleteSharedData  bool                   `protobuf:"varint,2,opt,name=deleteSharedData,proto3" json:"deleteSharedData,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateProfileDeletionResponse) Reset() {
	*x = UpdateProfileDeletionResponse{}
	mi := &file_v1_account_workflows_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileDeletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileDeletionResponse) ProtoMessage() {}

func (x *UpdateProfileDeletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_workflows_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileDeletionResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileDeletionResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_workflows_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileDeletionResponse) GetDeletionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTimestamp
	}
	return nil
}

func (x *UpdateProfileDeletionResponse) GetDeleteSharedData() bool {
	if x != nil {
		return x.DeleteSharedData
	}
	return false
}

type StartEmailBindingRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	FlowBinding             string                 `protobuf:"bytes,20,opt,name=flowBinding,proto3" json:"flowBinding,omitempty"`
	UserId                  string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email                   string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Purpose                 string                 `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Credentials             *Reauthentication      `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	ConfirmationLinkPattern string                 `protobuf:"bytes,5,opt,name=confirmationLinkPattern,proto3" json:"confirmationLinkPattern,omitempty"`
	RedirectUri             string                 `protobuf:"bytes,6,opt,name=redirectUri,proto3" json:"redirectUri,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StartEmailBindingRequest) Reset() {
	*x = StartEmailBindingRequest{}
	mi := &file_v1_account_workflows_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEmailBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEmailBindingRequest) ProtoMessage() {}

func (x *StartEmailBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_workflows_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEmailBindingRequest.ProtoReflect.Descriptor instead.
func (*StartEmailBindingRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_workflows_proto_rawDescGZIP(), []int{3}
}

func (x *StartEmailBindingRequest) GetFlowBinding() string {
	if x != nil {
		return x.FlowBinding
	}
	return ""
}

func (x *StartEmailBindingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartEmailBindingRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StartEmailBindingRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *StartEmailBindingRequest) GetCredentials() *Reauthentication {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *StartEmailBindingRequest) GetConfirmationLinkPattern() string {
	if x != nil {
		return x.ConfirmationLinkPattern
	}
	return ""
}

func (x *StartEmailBindingRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type StartEmailBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEmailBindingResponse) Reset() {
	*x = StartEmailBindingResponse{}
	mi := &file_v1_account_workflows_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEmailBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEmailBindingResponse) ProtoMessage() {}

func (x *StartEmailBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_workflows_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEmailBindingResponse.ProtoReflect.Descriptor instead.
func (*StartEmailBindingResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_workflows_proto_rawDescGZIP(), []int{4}
}

type ConfirmEmailBindingRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	FlowBinding             string                 `protobuf:"bytes,20,opt,name=flowBinding,proto3" json:"flowBinding,omitempty"`
	Token                   string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ConfirmationLinkPattern string                 `protobuf:"bytes,2,opt,name=confirmationLinkPattern,proto3" json:"confirmationLinkPattern,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConfirmEmailBindingRequest) Reset() {
	*x = ConfirmEmailBindingRequest{}
	mi := &file_v1_account_workflows_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailBindingRequest) ProtoMessage() {}

func (x *ConfirmEmailBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_workflows_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailBindingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmEmailBindingRequest) Descriptor() ([]byte, []int) {
	return file_v1_account_workflows_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmEmailBindingRequest) GetFlowBinding() string {
	if x != nil {
		return x.FlowBinding
	}
	return ""
}

func (x *ConfirmEmailBindingRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConfirmEmailBindingRequest) GetConfirmationLinkPattern() string {
	if x != nil {
		return x.ConfirmationLinkPattern
	}
	return ""
}

type ConfirmEmailBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purpose       string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmEmailBindingResponse) Reset() {
	*x = ConfirmEmailBindingResponse{}
	mi := &file_v1_account_workflows_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailBindingResponse) ProtoMessage() {}

func (x *ConfirmEmailBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_account_workflows_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailBindingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmEmailBindingResponse) Descriptor() ([]byte, []int) {
	return file_v1_account_workflows_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmEmailBindingResponse) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *ConfirmEmailBindingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_v1_account_workflows_proto protoreflect.FileDescriptor

const file_v1_account_workflows_proto_rawDesc = "" +
	"\n" +
	"\x1av1/account-workflows.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\x10Reauthentication\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\aidToken\x18\x03 \x01(\tR\aidToken\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\"\x84\x01\n" +
	"\x1cUpdateProfileDeletionRequest\x12 \n" +
	"\vflowBinding\x18\x14 \x01(\tR\vflowBinding\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x10deleteSharedData\x18\x02 \x01(\bR\x10deleteSharedData\"\x95\x01\n" +
	"\x1dUpdateProfileDeletionResponse\x12H\n" +
	"\x11deletionTimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x11deletionTimestamp\x12*\n" +
	"\x10deleteSharedData\x18\x02 \x01(\bR\x10deleteSharedData\"\x98\x02\n" +
	"\x18StartEmailBindingRequest\x12 \n" +
	"\vflowBinding\x18\x14 \x01(\tR\vflowBinding\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x126\n" +
	"\vcredentials\x18\x04 \x01(\v2\x14.v1.ReauthenticationR\vcredentials\x128\n" +
	"\x17confirmationLinkPattern\x18\x05 \x01(\tR\x17confirmationLinkPattern\x12 \n" +
	"\vredirectUri\x18\x06 \x01(\tR\vredirectUri\"\x1b\n" +
	"\x19StartEmailBindingResponse\"\x8e\x01\n" +
	"\x1aConfirmEmailBindingRequest\x12 \n" +
	"\vflowBinding\x18\x14 \x01(\tR\vflowBinding\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x128\n" +
	"\x17confirmationLinkPattern\x18\x02 \x01(\tR\x17confirmationLinkPattern\"O\n" +
	"\x1bConfirmEmailBindingResponse\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06statusB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_account_workflows_proto_rawDescOnce sync.Once
	file_v1_account_workflows_proto_rawDescData []byte
)

func file_v1_account_workflows_proto_rawDescGZIP() []byte {
	file_v1_account_workflows_proto_rawDescOnce.Do(func() {
		file_v1_account_workflows_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_account_workflows_proto_rawDesc), len(file_v1_account_workflows_proto_rawDesc)))
	})
	return file_v1_account_workflows_proto_rawDescData
}

var file_v1_account_workflows_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_account_workflows_proto_goTypes = []any{
	(*Reauthentication)(nil),              // 0: v1.Reauthentication
	(*UpdateProfileDeletionRequest)(nil),  // 1: v1.UpdateProfileDeletionRequest
	(*UpdateProfileDeletionResponse)(nil), // 2: v1.UpdateProfileDeletionResponse
	(*StartEmailBindingRequest)(nil),      // 3: v1.StartEmailBindingRequest
	(*StartEmailBindingResponse)(nil),     // 4: v1.StartEmailBindingResponse
	(*ConfirmEmailBindingRequest)(nil),    // 5: v1.ConfirmEmailBindingRequest
	(*ConfirmEmailBindingResponse)(nil),   // 6: v1.ConfirmEmailBindingResponse
	(*timestamppb.Timestamp)(nil),         // 7: google.protobuf.Timestamp
}
var file_v1_account_workflows_proto_depIdxs = []int32{
	7, // 0: v1.UpdateProfileDeletionResponse.deletionTimestamp:type_name -> google.protobuf.Timestamp
	0, // 1: v1.StartEmailBindingRequest.credentials:type_name -> v1.Reauthentication
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_account_workflows_proto_init() }
func file_v1_account_workflows_proto_init() {
	if File_v1_account_workflows_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_account_workflows_proto_rawDesc), len(file_v1_account_workflows_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_account_workflows_proto_goTypes,
		DependencyIndexes: file_v1_account_workflows_proto_depIdxs,
		MessageInfos:      file_v1_account_workflows_proto_msgTypes,
	}.Build()
	File_v1_account_workflows_proto = out.File
	file_v1_account_workflows_proto_goTypes = nil
	file_v1_account_workflows_proto_depIdxs = nil
}
