// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/activate-profile.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivateProfileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ActivationCode string                 `protobuf:"bytes,2,opt,name=activationCode,proto3" json:"activationCode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActivateProfileRequest) Reset() {
	*x = ActivateProfileRequest{}
	mi := &file_v1_activate_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProfileRequest) ProtoMessage() {}

func (x *ActivateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_activate_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProfileRequest.ProtoReflect.Descriptor instead.
func (*ActivateProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_activate_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ActivateProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActivateProfileRequest) GetActivationCode() string {
	if x != nil {
		return x.ActivationCode
	}
	return ""
}

type ActivateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateProfileResponse) Reset() {
	*x = ActivateProfileResponse{}
	mi := &file_v1_activate_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateProfileResponse) ProtoMessage() {}

func (x *ActivateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_activate_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateProfileResponse.ProtoReflect.Descriptor instead.
func (*ActivateProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_activate_profile_proto_rawDescGZIP(), []int{1}
}

func (x *ActivateProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_activate_profile_proto protoreflect.FileDescriptor

const file_v1_activate_profile_proto_rawDesc = "" +
	"\n" +
	"\x19v1/activate-profile.proto\x12\x02v1\"P\n" +
	"\x16ActivateProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0eactivationCode\x18\x02 \x01(\tR\x0eactivationCode\"3\n" +
	"\x17ActivateProfileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_activate_profile_proto_rawDescOnce sync.Once
	file_v1_activate_profile_proto_rawDescData []byte
)

func file_v1_activate_profile_proto_rawDescGZIP() []byte {
	file_v1_activate_profile_proto_rawDescOnce.Do(func() {
		file_v1_activate_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_activate_profile_proto_rawDesc), len(file_v1_activate_profile_proto_rawDesc)))
	})
	return file_v1_activate_profile_proto_rawDescData
}

var file_v1_activate_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_activate_profile_proto_goTypes = []any{
	(*ActivateProfileRequest)(nil),  // 0: v1.ActivateProfileRequest
	(*ActivateProfileResponse)(nil), // 1: v1.ActivateProfileResponse
}
var file_v1_activate_profile_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_activate_profile_proto_init() }
func file_v1_activate_profile_proto_init() {
	if File_v1_activate_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_activate_profile_proto_rawDesc), len(file_v1_activate_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_activate_profile_proto_goTypes,
		DependencyIndexes: file_v1_activate_profile_proto_depIdxs,
		MessageInfos:      file_v1_activate_profile_proto_msgTypes,
	}.Build()
	File_v1_activate_profile_proto = out.File
	file_v1_activate_profile_proto_goTypes = nil
	file_v1_activate_profile_proto_depIdxs = nil
}
