// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: v1/authentication.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthenticationService_ValidateSession_FullMethodName            = "/v1.AuthenticationService/ValidateSession"
	AuthenticationService_CreateAuthentication_FullMethodName       = "/v1.AuthenticationService/CreateAuthentication"
	AuthenticationService_GetAuthentication_FullMethodName          = "/v1.AuthenticationService/GetAuthentication"
	AuthenticationService_StartAuthenticationStep_FullMethodName    = "/v1.AuthenticationService/StartAuthenticationStep"
	AuthenticationService_GetAuthenticationStep_FullMethodName      = "/v1.AuthenticationService/GetAuthenticationStep"
	AuthenticationService_CompleteAuthenticationStep_FullMethodName = "/v1.AuthenticationService/CompleteAuthenticationStep"
	AuthenticationService_CreateSession_FullMethodName              = "/v1.AuthenticationService/CreateSession"
	AuthenticationService_RefreshSession_FullMethodName             = "/v1.AuthenticationService/RefreshSession"
	AuthenticationService_GetSessions_FullMethodName                = "/v1.AuthenticationService/GetSessions"
	AuthenticationService_RevokeSessions_FullMethodName             = "/v1.AuthenticationService/RevokeSessions"
	AuthenticationService_SetPassword_FullMethodName                = "/v1.AuthenticationService/SetPassword"
	AuthenticationService_StartPasswordReset_FullMethodName         = "/v1.AuthenticationService/StartPasswordReset"
	AuthenticationService_ConfirmPasswordReset_FullMethodName       = "/v1.AuthenticationService/ConfirmPasswordReset"
	AuthenticationService_SetUsername_FullMethodName                = "/v1.AuthenticationService/SetUsername"
	AuthenticationService_UsernameAvailability_FullMethodName       = "/v1.AuthenticationService/UsernameAvailability"
	AuthenticationService_ChangeEmail_FullMethodName                = "/v1.AuthenticationService/ChangeEmail"
	AuthenticationService_ConfirmEmail_FullMethodName               = "/v1.AuthenticationService/ConfirmEmail"
	AuthenticationService_RequestDeletion_FullMethodName            = "/v1.AuthenticationService/RequestDeletion"
	AuthenticationService_PatchDeletion_FullMethodName              = "/v1.AuthenticationService/PatchDeletion"
	AuthenticationService_CancelDeletion_FullMethodName             = "/v1.AuthenticationService/CancelDeletion"
	AuthenticationService_GetIdentities_FullMethodName              = "/v1.AuthenticationService/GetIdentities"
	AuthenticationService_LinkIdentity_FullMethodName               = "/v1.AuthenticationService/LinkIdentity"
	AuthenticationService_UnlinkIdentity_FullMethodName             = "/v1.AuthenticationService/UnlinkIdentity"
	AuthenticationService_PrepareIdentityOAuth_FullMethodName       = "/v1.AuthenticationService/PrepareIdentityOAuth"
	AuthenticationService_GetTotp_FullMethodName                    = "/v1.AuthenticationService/GetTotp"
	AuthenticationService_StartTotp_FullMethodName                  = "/v1.AuthenticationService/StartTotp"
	AuthenticationService_ConfirmTotp_FullMethodName                = "/v1.AuthenticationService/ConfirmTotp"
	AuthenticationService_DeleteTotp_FullMethodName                 = "/v1.AuthenticationService/DeleteTotp"
	AuthenticationService_GetPasskeys_FullMethodName                = "/v1.AuthenticationService/GetPasskeys"
	AuthenticationService_StartPasskeyRegistration_FullMethodName   = "/v1.AuthenticationService/StartPasskeyRegistration"
	AuthenticationService_RegisterPasskey_FullMethodName            = "/v1.AuthenticationService/RegisterPasskey"
	AuthenticationService_RenamePasskey_FullMethodName              = "/v1.AuthenticationService/RenamePasskey"
	AuthenticationService_DeletePasskey_FullMethodName              = "/v1.AuthenticationService/DeletePasskey"
	AuthenticationService_GetBackupCodes_FullMethodName             = "/v1.AuthenticationService/GetBackupCodes"
	AuthenticationService_RotateBackupCodes_FullMethodName          = "/v1.AuthenticationService/RotateBackupCodes"
)

// AuthenticationServiceClient is the client API for AuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthenticationServiceClient interface {
	ValidateSession(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateAuthentication(ctx context.Context, in *CreateAuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationState, error)
	GetAuthentication(ctx context.Context, in *FlowContext, opts ...grpc.CallOption) (*AuthenticationState, error)
	StartAuthenticationStep(ctx context.Context, in *StartAuthenticationStepRequest, opts ...grpc.CallOption) (*AuthenticationStep, error)
	GetAuthenticationStep(ctx context.Context, in *AuthenticationStepContext, opts ...grpc.CallOption) (*AuthenticationStep, error)
	CompleteAuthenticationStep(ctx context.Context, in *CompleteAuthenticationStepRequest, opts ...grpc.CallOption) (*CompleteAuthenticationStepResponse, error)
	CreateSession(ctx context.Context, in *CreateAuthenticatedSessionRequest, opts ...grpc.CallOption) (*AuthTokens, error)
	RefreshSession(ctx context.Context, in *RotateSessionRequest, opts ...grpc.CallOption) (*AuthTokens, error)
	GetSessions(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*AuthSessions, error)
	RevokeSessions(ctx context.Context, in *RevokeAuthSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetPassword(ctx context.Context, in *SetAccountPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StartPasswordReset(ctx context.Context, in *StartPasswordResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ConfirmPasswordReset(ctx context.Context, in *ConfirmPasswordResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetUsername(ctx context.Context, in *SetAccountUsernameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UsernameAvailability(ctx context.Context, in *AuthUsernameRequest, opts ...grpc.CallOption) (*AuthUsernameAvailability, error)
	ChangeEmail(ctx context.Context, in *ChangeAccountEmailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ConfirmEmail(ctx context.Context, in *ConfirmAccountEmailRequest, opts ...grpc.CallOption) (*ConfirmAccountEmailResponse, error)
	RequestDeletion(ctx context.Context, in *RequestAccountDeletionRequest, opts ...grpc.CallOption) (*AccountDeletion, error)
	PatchDeletion(ctx context.Context, in *PatchAccountDeletionRequest, opts ...grpc.CallOption) (*AccountDeletion, error)
	CancelDeletion(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetIdentities(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*AuthIdentities, error)
	LinkIdentity(ctx context.Context, in *LinkIdentityRequest, opts ...grpc.CallOption) (*LinkIdentityResponse, error)
	UnlinkIdentity(ctx context.Context, in *UnlinkIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrepareIdentityOAuth(ctx context.Context, in *PrepareIdentityOAuthRequest, opts ...grpc.CallOption) (*PreparedIdentityOAuth, error)
	GetTotp(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*TotpState, error)
	StartTotp(ctx context.Context, in *SensitiveAction, opts ...grpc.CallOption) (*TotpActivation, error)
	ConfirmTotp(ctx context.Context, in *ConfirmTotpRequest, opts ...grpc.CallOption) (*BackupCodes, error)
	DeleteTotp(ctx context.Context, in *SensitiveAction, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPasskeys(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*AuthPasskeys, error)
	StartPasskeyRegistration(ctx context.Context, in *SensitiveAction, opts ...grpc.CallOption) (*PasskeyRegistrationOptions, error)
	RegisterPasskey(ctx context.Context, in *RegisterAuthPasskeyRequest, opts ...grpc.CallOption) (*AuthPasskey, error)
	RenamePasskey(ctx context.Context, in *RenameAuthPasskeyRequest, opts ...grpc.CallOption) (*AuthPasskey, error)
	DeletePasskey(ctx context.Context, in *DeleteAuthPasskeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBackupCodes(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*BackupCodesState, error)
	RotateBackupCodes(ctx context.Context, in *SensitiveAction, opts ...grpc.CallOption) (*BackupCodes, error)
}

type authenticationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationServiceClient(cc grpc.ClientConnInterface) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) ValidateSession(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_ValidateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) CreateAuthentication(ctx context.Context, in *CreateAuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticationState)
	err := c.cc.Invoke(ctx, AuthenticationService_CreateAuthentication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetAuthentication(ctx context.Context, in *FlowContext, opts ...grpc.CallOption) (*AuthenticationState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticationState)
	err := c.cc.Invoke(ctx, AuthenticationService_GetAuthentication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) StartAuthenticationStep(ctx context.Context, in *StartAuthenticationStepRequest, opts ...grpc.CallOption) (*AuthenticationStep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticationStep)
	err := c.cc.Invoke(ctx, AuthenticationService_StartAuthenticationStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetAuthenticationStep(ctx context.Context, in *AuthenticationStepContext, opts ...grpc.CallOption) (*AuthenticationStep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticationStep)
	err := c.cc.Invoke(ctx, AuthenticationService_GetAuthenticationStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) CompleteAuthenticationStep(ctx context.Context, in *CompleteAuthenticationStepRequest, opts ...grpc.CallOption) (*CompleteAuthenticationStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteAuthenticationStepResponse)
	err := c.cc.Invoke(ctx, AuthenticationService_CompleteAuthenticationStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) CreateSession(ctx context.Context, in *CreateAuthenticatedSessionRequest, opts ...grpc.CallOption) (*AuthTokens, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthTokens)
	err := c.cc.Invoke(ctx, AuthenticationService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) RefreshSession(ctx context.Context, in *RotateSessionRequest, opts ...grpc.CallOption) (*AuthTokens, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthTokens)
	err := c.cc.Invoke(ctx, AuthenticationService_RefreshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetSessions(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*AuthSessions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthSessions)
	err := c.cc.Invoke(ctx, AuthenticationService_GetSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) RevokeSessions(ctx context.Context, in *RevokeAuthSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_RevokeSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) SetPassword(ctx context.Context, in *SetAccountPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_SetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) StartPasswordReset(ctx context.Context, in *StartPasswordResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_StartPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) ConfirmPasswordReset(ctx context.Context, in *ConfirmPasswordResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_ConfirmPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) SetUsername(ctx context.Context, in *SetAccountUsernameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_SetUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) UsernameAvailability(ctx context.Context, in *AuthUsernameRequest, opts ...grpc.CallOption) (*AuthUsernameAvailability, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthUsernameAvailability)
	err := c.cc.Invoke(ctx, AuthenticationService_UsernameAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) ChangeEmail(ctx context.Context, in *ChangeAccountEmailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_ChangeEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) ConfirmEmail(ctx context.Context, in *ConfirmAccountEmailRequest, opts ...grpc.CallOption) (*ConfirmAccountEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmAccountEmailResponse)
	err := c.cc.Invoke(ctx, AuthenticationService_ConfirmEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) RequestDeletion(ctx context.Context, in *RequestAccountDeletionRequest, opts ...grpc.CallOption) (*AccountDeletion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountDeletion)
	err := c.cc.Invoke(ctx, AuthenticationService_RequestDeletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) PatchDeletion(ctx context.Context, in *PatchAccountDeletionRequest, opts ...grpc.CallOption) (*AccountDeletion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountDeletion)
	err := c.cc.Invoke(ctx, AuthenticationService_PatchDeletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) CancelDeletion(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_CancelDeletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetIdentities(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*AuthIdentities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthIdentities)
	err := c.cc.Invoke(ctx, AuthenticationService_GetIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) LinkIdentity(ctx context.Context, in *LinkIdentityRequest, opts ...grpc.CallOption) (*LinkIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkIdentityResponse)
	err := c.cc.Invoke(ctx, AuthenticationService_LinkIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) UnlinkIdentity(ctx context.Context, in *UnlinkIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_UnlinkIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) PrepareIdentityOAuth(ctx context.Context, in *PrepareIdentityOAuthRequest, opts ...grpc.CallOption) (*PreparedIdentityOAuth, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreparedIdentityOAuth)
	err := c.cc.Invoke(ctx, AuthenticationService_PrepareIdentityOAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetTotp(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*TotpState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TotpState)
	err := c.cc.Invoke(ctx, AuthenticationService_GetTotp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) StartTotp(ctx context.Context, in *SensitiveAction, opts ...grpc.CallOption) (*TotpActivation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TotpActivation)
	err := c.cc.Invoke(ctx, AuthenticationService_StartTotp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) ConfirmTotp(ctx context.Context, in *ConfirmTotpRequest, opts ...grpc.CallOption) (*BackupCodes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupCodes)
	err := c.cc.Invoke(ctx, AuthenticationService_ConfirmTotp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) DeleteTotp(ctx context.Context, in *SensitiveAction, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_DeleteTotp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetPasskeys(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*AuthPasskeys, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthPasskeys)
	err := c.cc.Invoke(ctx, AuthenticationService_GetPasskeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) StartPasskeyRegistration(ctx context.Context, in *SensitiveAction, opts ...grpc.CallOption) (*PasskeyRegistrationOptions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasskeyRegistrationOptions)
	err := c.cc.Invoke(ctx, AuthenticationService_StartPasskeyRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) RegisterPasskey(ctx context.Context, in *RegisterAuthPasskeyRequest, opts ...grpc.CallOption) (*AuthPasskey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthPasskey)
	err := c.cc.Invoke(ctx, AuthenticationService_RegisterPasskey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) RenamePasskey(ctx context.Context, in *RenameAuthPasskeyRequest, opts ...grpc.CallOption) (*AuthPasskey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthPasskey)
	err := c.cc.Invoke(ctx, AuthenticationService_RenamePasskey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) DeletePasskey(ctx context.Context, in *DeleteAuthPasskeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AuthenticationService_DeletePasskey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetBackupCodes(ctx context.Context, in *AuthPrincipal, opts ...grpc.CallOption) (*BackupCodesState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupCodesState)
	err := c.cc.Invoke(ctx, AuthenticationService_GetBackupCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) RotateBackupCodes(ctx context.Context, in *SensitiveAction, opts ...grpc.CallOption) (*BackupCodes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupCodes)
	err := c.cc.Invoke(ctx, AuthenticationService_RotateBackupCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServiceServer is the server API for AuthenticationService service.
// All implementations must embed UnimplementedAuthenticationServiceServer
// for forward compatibility.
type AuthenticationServiceServer interface {
	ValidateSession(context.Context, *AuthPrincipal) (*emptypb.Empty, error)
	CreateAuthentication(context.Context, *CreateAuthenticationRequest) (*AuthenticationState, error)
	GetAuthentication(context.Context, *FlowContext) (*AuthenticationState, error)
	StartAuthenticationStep(context.Context, *StartAuthenticationStepRequest) (*AuthenticationStep, error)
	GetAuthenticationStep(context.Context, *AuthenticationStepContext) (*AuthenticationStep, error)
	CompleteAuthenticationStep(context.Context, *CompleteAuthenticationStepRequest) (*CompleteAuthenticationStepResponse, error)
	CreateSession(context.Context, *CreateAuthenticatedSessionRequest) (*AuthTokens, error)
	RefreshSession(context.Context, *RotateSessionRequest) (*AuthTokens, error)
	GetSessions(context.Context, *AuthPrincipal) (*AuthSessions, error)
	RevokeSessions(context.Context, *RevokeAuthSessionRequest) (*emptypb.Empty, error)
	SetPassword(context.Context, *SetAccountPasswordRequest) (*emptypb.Empty, error)
	StartPasswordReset(context.Context, *StartPasswordResetRequest) (*emptypb.Empty, error)
	ConfirmPasswordReset(context.Context, *ConfirmPasswordResetRequest) (*emptypb.Empty, error)
	SetUsername(context.Context, *SetAccountUsernameRequest) (*emptypb.Empty, error)
	UsernameAvailability(context.Context, *AuthUsernameRequest) (*AuthUsernameAvailability, error)
	ChangeEmail(context.Context, *ChangeAccountEmailRequest) (*emptypb.Empty, error)
	ConfirmEmail(context.Context, *ConfirmAccountEmailRequest) (*ConfirmAccountEmailResponse, error)
	RequestDeletion(context.Context, *RequestAccountDeletionRequest) (*AccountDeletion, error)
	PatchDeletion(context.Context, *PatchAccountDeletionRequest) (*AccountDeletion, error)
	CancelDeletion(context.Context, *AuthPrincipal) (*emptypb.Empty, error)
	GetIdentities(context.Context, *AuthPrincipal) (*AuthIdentities, error)
	LinkIdentity(context.Context, *LinkIdentityRequest) (*LinkIdentityResponse, error)
	UnlinkIdentity(context.Context, *UnlinkIdentityRequest) (*emptypb.Empty, error)
	PrepareIdentityOAuth(context.Context, *PrepareIdentityOAuthRequest) (*PreparedIdentityOAuth, error)
	GetTotp(context.Context, *AuthPrincipal) (*TotpState, error)
	StartTotp(context.Context, *SensitiveAction) (*TotpActivation, error)
	ConfirmTotp(context.Context, *ConfirmTotpRequest) (*BackupCodes, error)
	DeleteTotp(context.Context, *SensitiveAction) (*emptypb.Empty, error)
	GetPasskeys(context.Context, *AuthPrincipal) (*AuthPasskeys, error)
	StartPasskeyRegistration(context.Context, *SensitiveAction) (*PasskeyRegistrationOptions, error)
	RegisterPasskey(context.Context, *RegisterAuthPasskeyRequest) (*AuthPasskey, error)
	RenamePasskey(context.Context, *RenameAuthPasskeyRequest) (*AuthPasskey, error)
	DeletePasskey(context.Context, *DeleteAuthPasskeyRequest) (*emptypb.Empty, error)
	GetBackupCodes(context.Context, *AuthPrincipal) (*BackupCodesState, error)
	RotateBackupCodes(context.Context, *SensitiveAction) (*BackupCodes, error)
	mustEmbedUnimplementedAuthenticationServiceServer()
}

// UnimplementedAuthenticationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthenticationServiceServer struct{}

func (UnimplementedAuthenticationServiceServer) ValidateSession(context.Context, *AuthPrincipal) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSession not implemented")
}
func (UnimplementedAuthenticationServiceServer) CreateAuthentication(context.Context, *CreateAuthenticationRequest) (*AuthenticationState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuthentication not implemented")
}
func (UnimplementedAuthenticationServiceServer) GetAuthentication(context.Context, *FlowContext) (*AuthenticationState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthentication not implemented")
}
func (UnimplementedAuthenticationServiceServer) StartAuthenticationStep(context.Context, *StartAuthenticationStepRequest) (*AuthenticationStep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAuthenticationStep not implemented")
}
func (UnimplementedAuthenticationServiceServer) GetAuthenticationStep(context.Context, *AuthenticationStepContext) (*AuthenticationStep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthenticationStep not implemented")
}
func (UnimplementedAuthenticationServiceServer) CompleteAuthenticationStep(context.Context, *CompleteAuthenticationStepRequest) (*CompleteAuthenticationStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteAuthenticationStep not implemented")
}
func (UnimplementedAuthenticationServiceServer) CreateSession(context.Context, *CreateAuthenticatedSessionRequest) (*AuthTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAuthenticationServiceServer) RefreshSession(context.Context, *RotateSessionRequest) (*AuthTokens, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSession not implemented")
}
func (UnimplementedAuthenticationServiceServer) GetSessions(context.Context, *AuthPrincipal) (*AuthSessions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessions not implemented")
}
func (UnimplementedAuthenticationServiceServer) RevokeSessions(context.Context, *RevokeAuthSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeSessions not implemented")
}
func (UnimplementedAuthenticationServiceServer) SetPassword(context.Context, *SetAccountPasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassword not implemented")
}
func (UnimplementedAuthenticationServiceServer) StartPasswordReset(context.Context, *StartPasswordResetRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPasswordReset not implemented")
}
func (UnimplementedAuthenticationServiceServer) ConfirmPasswordReset(context.Context, *ConfirmPasswordResetRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPasswordReset not implemented")
}
func (UnimplementedAuthenticationServiceServer) SetUsername(context.Context, *SetAccountUsernameRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUsername not implemented")
}
func (UnimplementedAuthenticationServiceServer) UsernameAvailability(context.Context, *AuthUsernameRequest) (*AuthUsernameAvailability, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsernameAvailability not implemented")
}
func (UnimplementedAuthenticationServiceServer) ChangeEmail(context.Context, *ChangeAccountEmailRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEmail not implemented")
}
func (UnimplementedAuthenticationServiceServer) ConfirmEmail(context.Context, *ConfirmAccountEmailRequest) (*ConfirmAccountEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmEmail not implemented")
}
func (UnimplementedAuthenticationServiceServer) RequestDeletion(context.Context, *RequestAccountDeletionRequest) (*AccountDeletion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDeletion not implemented")
}
func (UnimplementedAuthenticationServiceServer) PatchDeletion(context.Context, *PatchAccountDeletionRequest) (*AccountDeletion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchDeletion not implemented")
}
func (UnimplementedAuthenticationServiceServer) CancelDeletion(context.Context, *AuthPrincipal) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelDeletion not implemented")
}
func (UnimplementedAuthenticationServiceServer) GetIdentities(context.Context, *AuthPrincipal) (*AuthIdentities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentities not implemented")
}
func (UnimplementedAuthenticationServiceServer) LinkIdentity(context.Context, *LinkIdentityRequest) (*LinkIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkIdentity not implemented")
}
func (UnimplementedAuthenticationServiceServer) UnlinkIdentity(context.Context, *UnlinkIdentityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlinkIdentity not implemented")
}
func (UnimplementedAuthenticationServiceServer) PrepareIdentityOAuth(context.Context, *PrepareIdentityOAuthRequest) (*PreparedIdentityOAuth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareIdentityOAuth not implemented")
}
func (UnimplementedAuthenticationServiceServer) GetTotp(context.Context, *AuthPrincipal) (*TotpState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotp not implemented")
}
func (UnimplementedAuthenticationServiceServer) StartTotp(context.Context, *SensitiveAction) (*TotpActivation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTotp not implemented")
}
func (UnimplementedAuthenticationServiceServer) ConfirmTotp(context.Context, *ConfirmTotpRequest) (*BackupCodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTotp not implemented")
}
func (UnimplementedAuthenticationServiceServer) DeleteTotp(context.Context, *SensitiveAction) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTotp not implemented")
}
func (UnimplementedAuthenticationServiceServer) GetPasskeys(context.Context, *AuthPrincipal) (*AuthPasskeys, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPasskeys not implemented")
}
func (UnimplementedAuthenticationServiceServer) StartPasskeyRegistration(context.Context, *SensitiveAction) (*PasskeyRegistrationOptions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPasskeyRegistration not implemented")
}
func (UnimplementedAuthenticationServiceServer) RegisterPasskey(context.Context, *RegisterAuthPasskeyRequest) (*AuthPasskey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPasskey not implemented")
}
func (UnimplementedAuthenticationServiceServer) RenamePasskey(context.Context, *RenameAuthPasskeyRequest) (*AuthPasskey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenamePasskey not implemented")
}
func (UnimplementedAuthenticationServiceServer) DeletePasskey(context.Context, *DeleteAuthPasskeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePasskey not implemented")
}
func (UnimplementedAuthenticationServiceServer) GetBackupCodes(context.Context, *AuthPrincipal) (*BackupCodesState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackupCodes not implemented")
}
func (UnimplementedAuthenticationServiceServer) RotateBackupCodes(context.Context, *SensitiveAction) (*BackupCodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateBackupCodes not implemented")
}
func (UnimplementedAuthenticationServiceServer) mustEmbedUnimplementedAuthenticationServiceServer() {}
func (UnimplementedAuthenticationServiceServer) testEmbeddedByValue()                               {}

// UnsafeAuthenticationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenticationServiceServer will
// result in compilation errors.
type UnsafeAuthenticationServiceServer interface {
	mustEmbedUnimplementedAuthenticationServiceServer()
}

func RegisterAuthenticationServiceServer(s grpc.ServiceRegistrar, srv AuthenticationServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthenticationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthenticationService_ServiceDesc, srv)
}

func _AuthenticationService_ValidateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthPrincipal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).ValidateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_ValidateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).ValidateSession(ctx, req.(*AuthPrincipal))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_CreateAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).CreateAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_CreateAuthentication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).CreateAuthentication(ctx, req.(*CreateAuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlowContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_GetAuthentication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetAuthentication(ctx, req.(*FlowContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_StartAuthenticationStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAuthenticationStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).StartAuthenticationStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_StartAuthenticationStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).StartAuthenticationStep(ctx, req.(*StartAuthenticationStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetAuthenticationStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticationStepContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetAuthenticationStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_GetAuthenticationStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetAuthenticationStep(ctx, req.(*AuthenticationStepContext))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_CompleteAuthenticationStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteAuthenticationStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).CompleteAuthenticationStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_CompleteAuthenticationStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).CompleteAuthenticationStep(ctx, req.(*CompleteAuthenticationStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthenticatedSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).CreateSession(ctx, req.(*CreateAuthenticatedSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_RefreshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).RefreshSession(ctx, req.(*RotateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthPrincipal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_GetSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetSessions(ctx, req.(*AuthPrincipal))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_RevokeSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAuthSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).RevokeSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_RevokeSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).RevokeSessions(ctx, req.(*RevokeAuthSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAccountPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_SetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).SetPassword(ctx, req.(*SetAccountPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_StartPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).StartPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_StartPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).StartPasswordReset(ctx, req.(*StartPasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_ConfirmPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).ConfirmPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_ConfirmPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).ConfirmPasswordReset(ctx, req.(*ConfirmPasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_SetUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAccountUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).SetUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_SetUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).SetUsername(ctx, req.(*SetAccountUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_UsernameAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).UsernameAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_UsernameAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).UsernameAvailability(ctx, req.(*AuthUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_ChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAccountEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).ChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_ChangeEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).ChangeEmail(ctx, req.(*ChangeAccountEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_ConfirmEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmAccountEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).ConfirmEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_ConfirmEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).ConfirmEmail(ctx, req.(*ConfirmAccountEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_RequestDeletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAccountDeletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).RequestDeletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_RequestDeletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).RequestDeletion(ctx, req.(*RequestAccountDeletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_PatchDeletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchAccountDeletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).PatchDeletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_PatchDeletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).PatchDeletion(ctx, req.(*PatchAccountDeletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_CancelDeletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthPrincipal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).CancelDeletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_CancelDeletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).CancelDeletion(ctx, req.(*AuthPrincipal))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthPrincipal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_GetIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetIdentities(ctx, req.(*AuthPrincipal))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_LinkIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).LinkIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_LinkIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).LinkIdentity(ctx, req.(*LinkIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_UnlinkIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).UnlinkIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_UnlinkIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).UnlinkIdentity(ctx, req.(*UnlinkIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_PrepareIdentityOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareIdentityOAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).PrepareIdentityOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_PrepareIdentityOAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).PrepareIdentityOAuth(ctx, req.(*PrepareIdentityOAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetTotp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthPrincipal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetTotp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_GetTotp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetTotp(ctx, req.(*AuthPrincipal))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_StartTotp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensitiveAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).StartTotp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_StartTotp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).StartTotp(ctx, req.(*SensitiveAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_ConfirmTotp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTotpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).ConfirmTotp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_ConfirmTotp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).ConfirmTotp(ctx, req.(*ConfirmTotpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_DeleteTotp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensitiveAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).DeleteTotp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_DeleteTotp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).DeleteTotp(ctx, req.(*SensitiveAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetPasskeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthPrincipal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetPasskeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_GetPasskeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetPasskeys(ctx, req.(*AuthPrincipal))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_StartPasskeyRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensitiveAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).StartPasskeyRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_StartPasskeyRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).StartPasskeyRegistration(ctx, req.(*SensitiveAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_RegisterPasskey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAuthPasskeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).RegisterPasskey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_RegisterPasskey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).RegisterPasskey(ctx, req.(*RegisterAuthPasskeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_RenamePasskey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameAuthPasskeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).RenamePasskey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_RenamePasskey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).RenamePasskey(ctx, req.(*RenameAuthPasskeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_DeletePasskey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAuthPasskeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).DeletePasskey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_DeletePasskey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).DeletePasskey(ctx, req.(*DeleteAuthPasskeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetBackupCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthPrincipal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetBackupCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_GetBackupCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetBackupCodes(ctx, req.(*AuthPrincipal))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_RotateBackupCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensitiveAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).RotateBackupCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_RotateBackupCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).RotateBackupCodes(ctx, req.(*SensitiveAction))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthenticationService_ServiceDesc is the grpc.ServiceDesc for AuthenticationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthenticationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateSession",
			Handler:    _AuthenticationService_ValidateSession_Handler,
		},
		{
			MethodName: "CreateAuthentication",
			Handler:    _AuthenticationService_CreateAuthentication_Handler,
		},
		{
			MethodName: "GetAuthentication",
			Handler:    _AuthenticationService_GetAuthentication_Handler,
		},
		{
			MethodName: "StartAuthenticationStep",
			Handler:    _AuthenticationService_StartAuthenticationStep_Handler,
		},
		{
			MethodName: "GetAuthenticationStep",
			Handler:    _AuthenticationService_GetAuthenticationStep_Handler,
		},
		{
			MethodName: "CompleteAuthenticationStep",
			Handler:    _AuthenticationService_CompleteAuthenticationStep_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _AuthenticationService_CreateSession_Handler,
		},
		{
			MethodName: "RefreshSession",
			Handler:    _AuthenticationService_RefreshSession_Handler,
		},
		{
			MethodName: "GetSessions",
			Handler:    _AuthenticationService_GetSessions_Handler,
		},
		{
			MethodName: "RevokeSessions",
			Handler:    _AuthenticationService_RevokeSessions_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _AuthenticationService_SetPassword_Handler,
		},
		{
			MethodName: "StartPasswordReset",
			Handler:    _AuthenticationService_StartPasswordReset_Handler,
		},
		{
			MethodName: "ConfirmPasswordReset",
			Handler:    _AuthenticationService_ConfirmPasswordReset_Handler,
		},
		{
			MethodName: "SetUsername",
			Handler:    _AuthenticationService_SetUsername_Handler,
		},
		{
			MethodName: "UsernameAvailability",
			Handler:    _AuthenticationService_UsernameAvailability_Handler,
		},
		{
			MethodName: "ChangeEmail",
			Handler:    _AuthenticationService_ChangeEmail_Handler,
		},
		{
			MethodName: "ConfirmEmail",
			Handler:    _AuthenticationService_ConfirmEmail_Handler,
		},
		{
			MethodName: "RequestDeletion",
			Handler:    _AuthenticationService_RequestDeletion_Handler,
		},
		{
			MethodName: "PatchDeletion",
			Handler:    _AuthenticationService_PatchDeletion_Handler,
		},
		{
			MethodName: "CancelDeletion",
			Handler:    _AuthenticationService_CancelDeletion_Handler,
		},
		{
			MethodName: "GetIdentities",
			Handler:    _AuthenticationService_GetIdentities_Handler,
		},
		{
			MethodName: "LinkIdentity",
			Handler:    _AuthenticationService_LinkIdentity_Handler,
		},
		{
			MethodName: "UnlinkIdentity",
			Handler:    _AuthenticationService_UnlinkIdentity_Handler,
		},
		{
			MethodName: "PrepareIdentityOAuth",
			Handler:    _AuthenticationService_PrepareIdentityOAuth_Handler,
		},
		{
			MethodName: "GetTotp",
			Handler:    _AuthenticationService_GetTotp_Handler,
		},
		{
			MethodName: "StartTotp",
			Handler:    _AuthenticationService_StartTotp_Handler,
		},
		{
			MethodName: "ConfirmTotp",
			Handler:    _AuthenticationService_ConfirmTotp_Handler,
		},
		{
			MethodName: "DeleteTotp",
			Handler:    _AuthenticationService_DeleteTotp_Handler,
		},
		{
			MethodName: "GetPasskeys",
			Handler:    _AuthenticationService_GetPasskeys_Handler,
		},
		{
			MethodName: "StartPasskeyRegistration",
			Handler:    _AuthenticationService_StartPasskeyRegistration_Handler,
		},
		{
			MethodName: "RegisterPasskey",
			Handler:    _AuthenticationService_RegisterPasskey_Handler,
		},
		{
			MethodName: "RenamePasskey",
			Handler:    _AuthenticationService_RenamePasskey_Handler,
		},
		{
			MethodName: "DeletePasskey",
			Handler:    _AuthenticationService_DeletePasskey_Handler,
		},
		{
			MethodName: "GetBackupCodes",
			Handler:    _AuthenticationService_GetBackupCodes_Handler,
		},
		{
			MethodName: "RotateBackupCodes",
			Handler:    _AuthenticationService_RotateBackupCodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/authentication.proto",
}
