// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/auth-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_auth_service_proto protoreflect.FileDescriptor

const file_v1_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x15v1/auth-service.proto\x12\x02v1\x1a\x10v1/sign-up.proto\x1a\x19v1/activate-profile.proto\x1a\x10v1/session.proto\x1a\x10v1/sign-in.proto\x1a$v1/get-access-token-public-key.proto\x1a\x18v1/refresh-session.proto\x1a\x11v1/sign-out.proto\x1a\x16v1/get-auth-info.proto\x1a$v1/get-profile-deletion-status.proto\x1a\x17v1/delete-profile.proto\x1a\x1ev1/cancel-delete-profile.proto\x1a\x1dv1/request-google-oauth.proto\x1a\x17v1/sign-in-google.proto\x1a\x1dv1/sign-in-google-token.proto\x1a\x17v1/connect-google.proto\x1a!v1/delete-google-connection.proto\x1a\x19v1/request-vk-oauth.proto\x1a\x13v1/sign-in-vk.proto\x1a\x13v1/connect-vk.proto\x1a\x1dv1/delete-vk-connection.proto\x1a\x15v1/get-sessions.proto\x1a\x15v1/end-sessions.proto\x1a\x1fv1/request-password-reset.proto\x1a\x17v1/reset-password.proto\x1a\x18v1/change-password.proto\x1a\x1av1/get-visible-names.proto\x1a$v1/check-username-availability.proto\x1a\x15v1/set-username.proto2\xd1\x0f\n" +
	"\vAuthService\x12/\n" +
	"\x06SignUp\x12\x11.v1.SignUpRequest\x1a\x12.v1.SignUpResponse\x12J\n" +
	"\x0fActivateProfile\x12\x1a.v1.ActivateProfileRequest\x1a\x1b.v1.ActivateProfileResponse\x120\n" +
	"\x06SignIn\x12\x11.v1.SignInRequest\x1a\x13.v1.SessionResponse\x12b\n" +
	"\x17GetAccessTokenPublicKey\x12\".v1.GetAccessTokenPublicKeyRequest\x1a#.v1.GetAccessTokenPublicKeyResponse\x12@\n" +
	"\x0eRefreshSession\x12\x19.v1.RefreshSessionRequest\x1a\x13.v1.SessionResponse\x122\n" +
	"\aSignOut\x12\x12.v1.SignOutRequest\x1a\x13.v1.SignOutResponse\x12>\n" +
	"\vGetAuthInfo\x12\x16.v1.GetAuthInfoRequest\x1a\x17.v1.GetAuthInfoResponse\x12e\n" +
	"\x18GetProfileDeletionStatus\x12#.v1.GetProfileDeletionStatusRequest\x1a$.v1.GetProfileDeletionStatusResponse\x12D\n" +
	"\rDeleteProfile\x12\x18.v1.DeleteProfileRequest\x1a\x19.v1.DeleteProfileResponse\x12\\\n" +
	"\x15CancelProfileDeletion\x12 .v1.CancelProfileDeletionRequest\x1a!.v1.CancelProfileDeletionResponse\x12S\n" +
	"\x12RequestGoogleOAuth\x12\x1d.v1.RequestGoogleOAuthRequest\x1a\x1e.v1.RequestGoogleOAuthResponse\x12<\n" +
	"\fSignInGoogle\x12\x17.v1.SignInGoogleRequest\x1a\x13.v1.SessionResponse\x12F\n" +
	"\x11SignInGoogleToken\x12\x1c.v1.SignInGoogleTokenRequest\x1a\x13.v1.SessionResponse\x12D\n" +
	"\rConnectGoogle\x12\x18.v1.ConnectGoogleRequest\x1a\x19.v1.ConnectGoogleResponse\x12_\n" +
	"\x16DeleteGoogleConnection\x12!.v1.DeleteGoogleConnectionRequest\x1a\".v1.DeleteGoogleConnectionResponse\x12G\n" +
	"\x0eRequestVkOAuth\x12\x19.v1.RequestVkOAuthRequest\x1a\x1a.v1.RequestVkOAuthResponse\x124\n" +
	"\bSignInVk\x12\x13.v1.SignInVkRequest\x1a\x13.v1.SessionResponse\x128\n" +
	"\tConnectVk\x12\x14.v1.ConnectVkRequest\x1a\x15.v1.ConnectVkResponse\x12S\n" +
	"\x12DeleteVkConnection\x12\x1d.v1.DeleteVkConnectionRequest\x1a\x1e.v1.DeleteVkConnectionResponse\x12>\n" +
	"\vGetSessions\x12\x16.v1.GetSessionsRequest\x1a\x17.v1.GetSessionsResponse\x12>\n" +
	"\vEndSessions\x12\x16.v1.EndSessionsRequest\x1a\x17.v1.EndSessionsResponse\x12Y\n" +
	"\x14RequestPasswordReset\x12\x1f.v1.RequestPasswordResetRequest\x1a .v1.RequestPasswordResetResponse\x12D\n" +
	"\rResetPassword\x12\x18.v1.ResetPasswordRequest\x1a\x19.v1.ResetPasswordResponse\x12G\n" +
	"\x0eChangePassword\x12\x19.v1.ChangePasswordRequest\x1a\x1a.v1.ChangePasswordResponse\x12J\n" +
	"\x0fGetVisibleNames\x12\x1a.v1.GetVisibleNamesRequest\x1a\x1b.v1.GetVisibleNamesResponse\x12h\n" +
	"\x19CheckUsernameAvailability\x12$.v1.CheckUsernameAvailabilityRequest\x1a%.v1.CheckUsernameAvailabilityResponse\x12>\n" +
	"\vSetUsername\x12\x16.v1.SetUsernameRequest\x1a\x17.v1.SetUsernameResponseB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var file_v1_auth_service_proto_goTypes = []any{
	(*SignUpRequest)(nil),                     // 0: v1.SignUpRequest
	(*ActivateProfileRequest)(nil),            // 1: v1.ActivateProfileRequest
	(*SignInRequest)(nil),                     // 2: v1.SignInRequest
	(*GetAccessTokenPublicKeyRequest)(nil),    // 3: v1.GetAccessTokenPublicKeyRequest
	(*RefreshSessionRequest)(nil),             // 4: v1.RefreshSessionRequest
	(*SignOutRequest)(nil),                    // 5: v1.SignOutRequest
	(*GetAuthInfoRequest)(nil),                // 6: v1.GetAuthInfoRequest
	(*GetProfileDeletionStatusRequest)(nil),   // 7: v1.GetProfileDeletionStatusRequest
	(*DeleteProfileRequest)(nil),              // 8: v1.DeleteProfileRequest
	(*CancelProfileDeletionRequest)(nil),      // 9: v1.CancelProfileDeletionRequest
	(*RequestGoogleOAuthRequest)(nil),         // 10: v1.RequestGoogleOAuthRequest
	(*SignInGoogleRequest)(nil),               // 11: v1.SignInGoogleRequest
	(*SignInGoogleTokenRequest)(nil),          // 12: v1.SignInGoogleTokenRequest
	(*ConnectGoogleRequest)(nil),              // 13: v1.ConnectGoogleRequest
	(*DeleteGoogleConnectionRequest)(nil),     // 14: v1.DeleteGoogleConnectionRequest
	(*RequestVkOAuthRequest)(nil),             // 15: v1.RequestVkOAuthRequest
	(*SignInVkRequest)(nil),                   // 16: v1.SignInVkRequest
	(*ConnectVkRequest)(nil),                  // 17: v1.ConnectVkRequest
	(*DeleteVkConnectionRequest)(nil),         // 18: v1.DeleteVkConnectionRequest
	(*GetSessionsRequest)(nil),                // 19: v1.GetSessionsRequest
	(*EndSessionsRequest)(nil),                // 20: v1.EndSessionsRequest
	(*RequestPasswordResetRequest)(nil),       // 21: v1.RequestPasswordResetRequest
	(*ResetPasswordRequest)(nil),              // 22: v1.ResetPasswordRequest
	(*ChangePasswordRequest)(nil),             // 23: v1.ChangePasswordRequest
	(*GetVisibleNamesRequest)(nil),            // 24: v1.GetVisibleNamesRequest
	(*CheckUsernameAvailabilityRequest)(nil),  // 25: v1.CheckUsernameAvailabilityRequest
	(*SetUsernameRequest)(nil),                // 26: v1.SetUsernameRequest
	(*SignUpResponse)(nil),                    // 27: v1.SignUpResponse
	(*ActivateProfileResponse)(nil),           // 28: v1.ActivateProfileResponse
	(*SessionResponse)(nil),                   // 29: v1.SessionResponse
	(*GetAccessTokenPublicKeyResponse)(nil),   // 30: v1.GetAccessTokenPublicKeyResponse
	(*SignOutResponse)(nil),                   // 31: v1.SignOutResponse
	(*GetAuthInfoResponse)(nil),               // 32: v1.GetAuthInfoResponse
	(*GetProfileDeletionStatusResponse)(nil),  // 33: v1.GetProfileDeletionStatusResponse
	(*DeleteProfileResponse)(nil),             // 34: v1.DeleteProfileResponse
	(*CancelProfileDeletionResponse)(nil),     // 35: v1.CancelProfileDeletionResponse
	(*RequestGoogleOAuthResponse)(nil),        // 36: v1.RequestGoogleOAuthResponse
	(*ConnectGoogleResponse)(nil),             // 37: v1.ConnectGoogleResponse
	(*DeleteGoogleConnectionResponse)(nil),    // 38: v1.DeleteGoogleConnectionResponse
	(*RequestVkOAuthResponse)(nil),            // 39: v1.RequestVkOAuthResponse
	(*ConnectVkResponse)(nil),                 // 40: v1.ConnectVkResponse
	(*DeleteVkConnectionResponse)(nil),        // 41: v1.DeleteVkConnectionResponse
	(*GetSessionsResponse)(nil),               // 42: v1.GetSessionsResponse
	(*EndSessionsResponse)(nil),               // 43: v1.EndSessionsResponse
	(*RequestPasswordResetResponse)(nil),      // 44: v1.RequestPasswordResetResponse
	(*ResetPasswordResponse)(nil),             // 45: v1.ResetPasswordResponse
	(*ChangePasswordResponse)(nil),            // 46: v1.ChangePasswordResponse
	(*GetVisibleNamesResponse)(nil),           // 47: v1.GetVisibleNamesResponse
	(*CheckUsernameAvailabilityResponse)(nil), // 48: v1.CheckUsernameAvailabilityResponse
	(*SetUsernameResponse)(nil),               // 49: v1.SetUsernameResponse
}
var file_v1_auth_service_proto_depIdxs = []int32{
	0,  // 0: v1.AuthService.SignUp:input_type -> v1.SignUpRequest
	1,  // 1: v1.AuthService.ActivateProfile:input_type -> v1.ActivateProfileRequest
	2,  // 2: v1.AuthService.SignIn:input_type -> v1.SignInRequest
	3,  // 3: v1.AuthService.GetAccessTokenPublicKey:input_type -> v1.GetAccessTokenPublicKeyRequest
	4,  // 4: v1.AuthService.RefreshSession:input_type -> v1.RefreshSessionRequest
	5,  // 5: v1.AuthService.SignOut:input_type -> v1.SignOutRequest
	6,  // 6: v1.AuthService.GetAuthInfo:input_type -> v1.GetAuthInfoRequest
	7,  // 7: v1.AuthService.GetProfileDeletionStatus:input_type -> v1.GetProfileDeletionStatusRequest
	8,  // 8: v1.AuthService.DeleteProfile:input_type -> v1.DeleteProfileRequest
	9,  // 9: v1.AuthService.CancelProfileDeletion:input_type -> v1.CancelProfileDeletionRequest
	10, // 10: v1.AuthService.RequestGoogleOAuth:input_type -> v1.RequestGoogleOAuthRequest
	11, // 11: v1.AuthService.SignInGoogle:input_type -> v1.SignInGoogleRequest
	12, // 12: v1.AuthService.SignInGoogleToken:input_type -> v1.SignInGoogleTokenRequest
	13, // 13: v1.AuthService.ConnectGoogle:input_type -> v1.ConnectGoogleRequest
	14, // 14: v1.AuthService.DeleteGoogleConnection:input_type -> v1.DeleteGoogleConnectionRequest
	15, // 15: v1.AuthService.RequestVkOAuth:input_type -> v1.RequestVkOAuthRequest
	16, // 16: v1.AuthService.SignInVk:input_type -> v1.SignInVkRequest
	17, // 17: v1.AuthService.ConnectVk:input_type -> v1.ConnectVkRequest
	18, // 18: v1.AuthService.DeleteVkConnection:input_type -> v1.DeleteVkConnectionRequest
	19, // 19: v1.AuthService.GetSessions:input_type -> v1.GetSessionsRequest
	20, // 20: v1.AuthService.EndSessions:input_type -> v1.EndSessionsRequest
	21, // 21: v1.AuthService.RequestPasswordReset:input_type -> v1.RequestPasswordResetRequest
	22, // 22: v1.AuthService.ResetPassword:input_type -> v1.ResetPasswordRequest
	23, // 23: v1.AuthService.ChangePassword:input_type -> v1.ChangePasswordRequest
	24, // 24: v1.AuthService.GetVisibleNames:input_type -> v1.GetVisibleNamesRequest
	25, // 25: v1.AuthService.CheckUsernameAvailability:input_type -> v1.CheckUsernameAvailabilityRequest
	26, // 26: v1.AuthService.SetUsername:input_type -> v1.SetUsernameRequest
	27, // 27: v1.AuthService.SignUp:output_type -> v1.SignUpResponse
	28, // 28: v1.AuthService.ActivateProfile:output_type -> v1.ActivateProfileResponse
	29, // 29: v1.AuthService.SignIn:output_type -> v1.SessionResponse
	30, // 30: v1.AuthService.GetAccessTokenPublicKey:output_type -> v1.GetAccessTokenPublicKeyResponse
	29, // 31: v1.AuthService.RefreshSession:output_type -> v1.SessionResponse
	31, // 32: v1.AuthService.SignOut:output_type -> v1.SignOutResponse
	32, // 33: v1.AuthService.GetAuthInfo:output_type -> v1.GetAuthInfoResponse
	33, // 34: v1.AuthService.GetProfileDeletionStatus:output_type -> v1.GetProfileDeletionStatusResponse
	34, // 35: v1.AuthService.DeleteProfile:output_type -> v1.DeleteProfileResponse
	35, // 36: v1.AuthService.CancelProfileDeletion:output_type -> v1.CancelProfileDeletionResponse
	36, // 37: v1.AuthService.RequestGoogleOAuth:output_type -> v1.RequestGoogleOAuthResponse
	29, // 38: v1.AuthService.SignInGoogle:output_type -> v1.SessionResponse
	29, // 39: v1.AuthService.SignInGoogleToken:output_type -> v1.SessionResponse
	37, // 40: v1.AuthService.ConnectGoogle:output_type -> v1.ConnectGoogleResponse
	38, // 41: v1.AuthService.DeleteGoogleConnection:output_type -> v1.DeleteGoogleConnectionResponse
	39, // 42: v1.AuthService.RequestVkOAuth:output_type -> v1.RequestVkOAuthResponse
	29, // 43: v1.AuthService.SignInVk:output_type -> v1.SessionResponse
	40, // 44: v1.AuthService.ConnectVk:output_type -> v1.ConnectVkResponse
	41, // 45: v1.AuthService.DeleteVkConnection:output_type -> v1.DeleteVkConnectionResponse
	42, // 46: v1.AuthService.GetSessions:output_type -> v1.GetSessionsResponse
	43, // 47: v1.AuthService.EndSessions:output_type -> v1.EndSessionsResponse
	44, // 48: v1.AuthService.RequestPasswordReset:output_type -> v1.RequestPasswordResetResponse
	45, // 49: v1.AuthService.ResetPassword:output_type -> v1.ResetPasswordResponse
	46, // 50: v1.AuthService.ChangePassword:output_type -> v1.ChangePasswordResponse
	47, // 51: v1.AuthService.GetVisibleNames:output_type -> v1.GetVisibleNamesResponse
	48, // 52: v1.AuthService.CheckUsernameAvailability:output_type -> v1.CheckUsernameAvailabilityResponse
	49, // 53: v1.AuthService.SetUsername:output_type -> v1.SetUsernameResponse
	27, // [27:54] is the sub-list for method output_type
	0,  // [0:27] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_auth_service_proto_init() }
func file_v1_auth_service_proto_init() {
	if File_v1_auth_service_proto != nil {
		return
	}
	file_v1_sign_up_proto_init()
	file_v1_activate_profile_proto_init()
	file_v1_session_proto_init()
	file_v1_sign_in_proto_init()
	file_v1_get_access_token_public_key_proto_init()
	file_v1_refresh_session_proto_init()
	file_v1_sign_out_proto_init()
	file_v1_get_auth_info_proto_init()
	file_v1_get_profile_deletion_status_proto_init()
	file_v1_delete_profile_proto_init()
	file_v1_cancel_delete_profile_proto_init()
	file_v1_request_google_oauth_proto_init()
	file_v1_sign_in_google_proto_init()
	file_v1_sign_in_google_token_proto_init()
	file_v1_connect_google_proto_init()
	file_v1_delete_google_connection_proto_init()
	file_v1_request_vk_oauth_proto_init()
	file_v1_sign_in_vk_proto_init()
	file_v1_connect_vk_proto_init()
	file_v1_delete_vk_connection_proto_init()
	file_v1_get_sessions_proto_init()
	file_v1_end_sessions_proto_init()
	file_v1_request_password_reset_proto_init()
	file_v1_reset_password_proto_init()
	file_v1_change_password_proto_init()
	file_v1_get_visible_names_proto_init()
	file_v1_check_username_availability_proto_init()
	file_v1_set_username_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_auth_service_proto_rawDesc), len(file_v1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_auth_service_proto_goTypes,
		DependencyIndexes: file_v1_auth_service_proto_depIdxs,
	}.Build()
	File_v1_auth_service_proto = out.File
	file_v1_auth_service_proto_goTypes = nil
	file_v1_auth_service_proto_depIdxs = nil
}
