// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/cancel-delete-profile.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CancelProfileDeletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profileId,proto3" json:"profileId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelProfileDeletionRequest) Reset() {
	*x = CancelProfileDeletionRequest{}
	mi := &file_v1_cancel_delete_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelProfileDeletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelProfileDeletionRequest) ProtoMessage() {}

func (x *CancelProfileDeletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cancel_delete_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelProfileDeletionRequest.ProtoReflect.Descriptor instead.
func (*CancelProfileDeletionRequest) Descriptor() ([]byte, []int) {
	return file_v1_cancel_delete_profile_proto_rawDescGZIP(), []int{0}
}

func (x *CancelProfileDeletionRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type CancelProfileDeletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelProfileDeletionResponse) Reset() {
	*x = CancelProfileDeletionResponse{}
	mi := &file_v1_cancel_delete_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelProfileDeletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelProfileDeletionResponse) ProtoMessage() {}

func (x *CancelProfileDeletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cancel_delete_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelProfileDeletionResponse.ProtoReflect.Descriptor instead.
func (*CancelProfileDeletionResponse) Descriptor() ([]byte, []int) {
	return file_v1_cancel_delete_profile_proto_rawDescGZIP(), []int{1}
}

func (x *CancelProfileDeletionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_cancel_delete_profile_proto protoreflect.FileDescriptor

const file_v1_cancel_delete_profile_proto_rawDesc = "" +
	"\n" +
	"\x1ev1/cancel-delete-profile.proto\x12\x02v1\"<\n" +
	"\x1cCancelProfileDeletionRequest\x12\x1c\n" +
	"\tprofileId\x18\x01 \x01(\tR\tprofileId\"9\n" +
	"\x1dCancelProfileDeletionResponse\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_cancel_delete_profile_proto_rawDescOnce sync.Once
	file_v1_cancel_delete_profile_proto_rawDescData []byte
)

func file_v1_cancel_delete_profile_proto_rawDescGZIP() []byte {
	file_v1_cancel_delete_profile_proto_rawDescOnce.Do(func() {
		file_v1_cancel_delete_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_cancel_delete_profile_proto_rawDesc), len(file_v1_cancel_delete_profile_proto_rawDesc)))
	})
	return file_v1_cancel_delete_profile_proto_rawDescData
}

var file_v1_cancel_delete_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_cancel_delete_profile_proto_goTypes = []any{
	(*CancelProfileDeletionRequest)(nil),  // 0: v1.CancelProfileDeletionRequest
	(*CancelProfileDeletionResponse)(nil), // 1: v1.CancelProfileDeletionResponse
}
var file_v1_cancel_delete_profile_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_cancel_delete_profile_proto_init() }
func file_v1_cancel_delete_profile_proto_init() {
	if File_v1_cancel_delete_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_cancel_delete_profile_proto_rawDesc), len(file_v1_cancel_delete_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_cancel_delete_profile_proto_goTypes,
		DependencyIndexes: file_v1_cancel_delete_profile_proto_depIdxs,
		MessageInfos:      file_v1_cancel_delete_profile_proto_msgTypes,
	}.Build()
	File_v1_cancel_delete_profile_proto = out.File
	file_v1_cancel_delete_profile_proto_goTypes = nil
	file_v1_cancel_delete_profile_proto_depIdxs = nil
}
