// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/check-username-availability.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckUsernameAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameAvailabilityRequest) Reset() {
	*x = CheckUsernameAvailabilityRequest{}
	mi := &file_v1_check_username_availability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameAvailabilityRequest) ProtoMessage() {}

func (x *CheckUsernameAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_check_username_availability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckUsernameAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_v1_check_username_availability_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUsernameAvailabilityRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CheckUsernameAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameAvailabilityResponse) Reset() {
	*x = CheckUsernameAvailabilityResponse{}
	mi := &file_v1_check_username_availability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameAvailabilityResponse) ProtoMessage() {}

func (x *CheckUsernameAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_check_username_availability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckUsernameAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_v1_check_username_availability_proto_rawDescGZIP(), []int{1}
}

func (x *CheckUsernameAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_v1_check_username_availability_proto protoreflect.FileDescriptor

const file_v1_check_username_availability_proto_rawDesc = "" +
	"\n" +
	"$v1/check-username-availability.proto\x12\x02v1\">\n" +
	" CheckUsernameAvailabilityRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"A\n" +
	"!CheckUsernameAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailableB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_check_username_availability_proto_rawDescOnce sync.Once
	file_v1_check_username_availability_proto_rawDescData []byte
)

func file_v1_check_username_availability_proto_rawDescGZIP() []byte {
	file_v1_check_username_availability_proto_rawDescOnce.Do(func() {
		file_v1_check_username_availability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_check_username_availability_proto_rawDesc), len(file_v1_check_username_availability_proto_rawDesc)))
	})
	return file_v1_check_username_availability_proto_rawDescData
}

var file_v1_check_username_availability_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_check_username_availability_proto_goTypes = []any{
	(*CheckUsernameAvailabilityRequest)(nil),  // 0: v1.CheckUsernameAvailabilityRequest
	(*CheckUsernameAvailabilityResponse)(nil), // 1: v1.CheckUsernameAvailabilityResponse
}
var file_v1_check_username_availability_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_check_username_availability_proto_init() }
func file_v1_check_username_availability_proto_init() {
	if File_v1_check_username_availability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_check_username_availability_proto_rawDesc), len(file_v1_check_username_availability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_check_username_availability_proto_goTypes,
		DependencyIndexes: file_v1_check_username_availability_proto_depIdxs,
		MessageInfos:      file_v1_check_username_availability_proto_msgTypes,
	}.Build()
	File_v1_check_username_availability_proto = out.File
	file_v1_check_username_availability_proto_goTypes = nil
	file_v1_check_username_availability_proto_depIdxs = nil
}
