// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/connect-google.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectGoogleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,4,opt,name=redirectUrl,proto3" json:"redirectUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectGoogleRequest) Reset() {
	*x = ConnectGoogleRequest{}
	mi := &file_v1_connect_google_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectGoogleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectGoogleRequest) ProtoMessage() {}

func (x *ConnectGoogleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_connect_google_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectGoogleRequest.ProtoReflect.Descriptor instead.
func (*ConnectGoogleRequest) Descriptor() ([]byte, []int) {
	return file_v1_connect_google_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectGoogleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectGoogleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ConnectGoogleRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ConnectGoogleRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type ConnectGoogleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectGoogleResponse) Reset() {
	*x = ConnectGoogleResponse{}
	mi := &file_v1_connect_google_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectGoogleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectGoogleResponse) ProtoMessage() {}

func (x *ConnectGoogleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_connect_google_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectGoogleResponse.ProtoReflect.Descriptor instead.
func (*ConnectGoogleResponse) Descriptor() ([]byte, []int) {
	return file_v1_connect_google_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectGoogleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_connect_google_proto protoreflect.FileDescriptor

const file_v1_connect_google_proto_rawDesc = "" +
	"\n" +
	"\x17v1/connect-google.proto\x12\x02v1\"r\n" +
	"\x14ConnectGoogleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12 \n" +
	"\vredirectUrl\x18\x04 \x01(\tR\vredirectUrl\"1\n" +
	"\x15ConnectGoogleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_connect_google_proto_rawDescOnce sync.Once
	file_v1_connect_google_proto_rawDescData []byte
)

func file_v1_connect_google_proto_rawDescGZIP() []byte {
	file_v1_connect_google_proto_rawDescOnce.Do(func() {
		file_v1_connect_google_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_connect_google_proto_rawDesc), len(file_v1_connect_google_proto_rawDesc)))
	})
	return file_v1_connect_google_proto_rawDescData
}

var file_v1_connect_google_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_connect_google_proto_goTypes = []any{
	(*ConnectGoogleRequest)(nil),  // 0: v1.ConnectGoogleRequest
	(*ConnectGoogleResponse)(nil), // 1: v1.ConnectGoogleResponse
}
var file_v1_connect_google_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_connect_google_proto_init() }
func file_v1_connect_google_proto_init() {
	if File_v1_connect_google_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_connect_google_proto_rawDesc), len(file_v1_connect_google_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_connect_google_proto_goTypes,
		DependencyIndexes: file_v1_connect_google_proto_depIdxs,
		MessageInfos:      file_v1_connect_google_proto_msgTypes,
	}.Build()
	File_v1_connect_google_proto = out.File
	file_v1_connect_google_proto_goTypes = nil
	file_v1_connect_google_proto_depIdxs = nil
}
