// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/delete-google-connection.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteGoogleConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoogleConnectionRequest) Reset() {
	*x = DeleteGoogleConnectionRequest{}
	mi := &file_v1_delete_google_connection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoogleConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoogleConnectionRequest) ProtoMessage() {}

func (x *DeleteGoogleConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_delete_google_connection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoogleConnectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteGoogleConnectionRequest) Descriptor() ([]byte, []int) {
	return file_v1_delete_google_connection_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteGoogleConnectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGoogleConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoogleConnectionResponse) Reset() {
	*x = DeleteGoogleConnectionResponse{}
	mi := &file_v1_delete_google_connection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoogleConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoogleConnectionResponse) ProtoMessage() {}

func (x *DeleteGoogleConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_delete_google_connection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoogleConnectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteGoogleConnectionResponse) Descriptor() ([]byte, []int) {
	return file_v1_delete_google_connection_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteGoogleConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_delete_google_connection_proto protoreflect.FileDescriptor

const file_v1_delete_google_connection_proto_rawDesc = "" +
	"\n" +
	"!v1/delete-google-connection.proto\x12\x02v1\"/\n" +
	"\x1dDeleteGoogleConnectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x1eDeleteGoogleConnectionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_delete_google_connection_proto_rawDescOnce sync.Once
	file_v1_delete_google_connection_proto_rawDescData []byte
)

func file_v1_delete_google_connection_proto_rawDescGZIP() []byte {
	file_v1_delete_google_connection_proto_rawDescOnce.Do(func() {
		file_v1_delete_google_connection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_delete_google_connection_proto_rawDesc), len(file_v1_delete_google_connection_proto_rawDesc)))
	})
	return file_v1_delete_google_connection_proto_rawDescData
}

var file_v1_delete_google_connection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_delete_google_connection_proto_goTypes = []any{
	(*DeleteGoogleConnectionRequest)(nil),  // 0: v1.DeleteGoogleConnectionRequest
	(*DeleteGoogleConnectionResponse)(nil), // 1: v1.DeleteGoogleConnectionResponse
}
var file_v1_delete_google_connection_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_delete_google_connection_proto_init() }
func file_v1_delete_google_connection_proto_init() {
	if File_v1_delete_google_connection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_delete_google_connection_proto_rawDesc), len(file_v1_delete_google_connection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_delete_google_connection_proto_goTypes,
		DependencyIndexes: file_v1_delete_google_connection_proto_depIdxs,
		MessageInfos:      file_v1_delete_google_connection_proto_msgTypes,
	}.Build()
	File_v1_delete_google_connection_proto = out.File
	file_v1_delete_google_connection_proto_goTypes = nil
	file_v1_delete_google_connection_proto_depIdxs = nil
}
