// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/delete-profile.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteProfileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProfileId        string                 `protobuf:"bytes,1,opt,name=profileId,proto3" json:"profileId,omitempty"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DeleteSharedData bool                   `protobuf:"varint,3,opt,name=deleteSharedData,proto3" json:"deleteSharedData,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_v1_delete_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_delete_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_v1_delete_profile_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *DeleteProfileRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DeleteProfileRequest) GetDeleteSharedData() bool {
	if x != nil {
		return x.DeleteSharedData
	}
	return false
}

type DeleteProfileResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeletionTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deletionTimestamp,proto3" json:"deletionTimestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_v1_delete_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_delete_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_v1_delete_profile_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteProfileResponse) GetDeletionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTimestamp
	}
	return nil
}

var File_v1_delete_profile_proto protoreflect.FileDescriptor

const file_v1_delete_profile_proto_rawDesc = "" +
	"\n" +
	"\x17v1/delete-profile.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"|\n" +
	"\x14DeleteProfileRequest\x12\x1c\n" +
	"\tprofileId\x18\x01 \x01(\tR\tprofileId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12*\n" +
	"\x10deleteSharedData\x18\x03 \x01(\bR\x10deleteSharedData\"a\n" +
	"\x15DeleteProfileResponse\x12H\n" +
	"\x11deletionTimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x11deletionTimestampB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_delete_profile_proto_rawDescOnce sync.Once
	file_v1_delete_profile_proto_rawDescData []byte
)

func file_v1_delete_profile_proto_rawDescGZIP() []byte {
	file_v1_delete_profile_proto_rawDescOnce.Do(func() {
		file_v1_delete_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_delete_profile_proto_rawDesc), len(file_v1_delete_profile_proto_rawDesc)))
	})
	return file_v1_delete_profile_proto_rawDescData
}

var file_v1_delete_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_delete_profile_proto_goTypes = []any{
	(*DeleteProfileRequest)(nil),  // 0: v1.DeleteProfileRequest
	(*DeleteProfileResponse)(nil), // 1: v1.DeleteProfileResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_v1_delete_profile_proto_depIdxs = []int32{
	2, // 0: v1.DeleteProfileResponse.deletionTimestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_delete_profile_proto_init() }
func file_v1_delete_profile_proto_init() {
	if File_v1_delete_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_delete_profile_proto_rawDesc), len(file_v1_delete_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_delete_profile_proto_goTypes,
		DependencyIndexes: file_v1_delete_profile_proto_depIdxs,
		MessageInfos:      file_v1_delete_profile_proto_msgTypes,
	}.Build()
	File_v1_delete_profile_proto = out.File
	file_v1_delete_profile_proto_goTypes = nil
	file_v1_delete_profile_proto_depIdxs = nil
}
