// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/end-sessions.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sessions      []int64                `protobuf:"varint,2,rep,packed,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionsRequest) Reset() {
	*x = EndSessionsRequest{}
	mi := &file_v1_end_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionsRequest) ProtoMessage() {}

func (x *EndSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_end_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionsRequest.ProtoReflect.Descriptor instead.
func (*EndSessionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_end_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *EndSessionsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EndSessionsRequest) GetSessions() []int64 {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type EndSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionsResponse) Reset() {
	*x = EndSessionsResponse{}
	mi := &file_v1_end_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionsResponse) ProtoMessage() {}

func (x *EndSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_end_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionsResponse.ProtoReflect.Descriptor instead.
func (*EndSessionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_end_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *EndSessionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_end_sessions_proto protoreflect.FileDescriptor

const file_v1_end_sessions_proto_rawDesc = "" +
	"\n" +
	"\x15v1/end-sessions.proto\x12\x02v1\"@\n" +
	"\x12EndSessionsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsessions\x18\x02 \x03(\x03R\bsessions\"/\n" +
	"\x13EndSessionsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_end_sessions_proto_rawDescOnce sync.Once
	file_v1_end_sessions_proto_rawDescData []byte
)

func file_v1_end_sessions_proto_rawDescGZIP() []byte {
	file_v1_end_sessions_proto_rawDescOnce.Do(func() {
		file_v1_end_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_end_sessions_proto_rawDesc), len(file_v1_end_sessions_proto_rawDesc)))
	})
	return file_v1_end_sessions_proto_rawDescData
}

var file_v1_end_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_end_sessions_proto_goTypes = []any{
	(*EndSessionsRequest)(nil),  // 0: v1.EndSessionsRequest
	(*EndSessionsResponse)(nil), // 1: v1.EndSessionsResponse
}
var file_v1_end_sessions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_end_sessions_proto_init() }
func file_v1_end_sessions_proto_init() {
	if File_v1_end_sessions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_end_sessions_proto_rawDesc), len(file_v1_end_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_end_sessions_proto_goTypes,
		DependencyIndexes: file_v1_end_sessions_proto_depIdxs,
		MessageInfos:      file_v1_end_sessions_proto_msgTypes,
	}.Build()
	File_v1_end_sessions_proto = out.File
	file_v1_end_sessions_proto_goTypes = nil
	file_v1_end_sessions_proto_depIdxs = nil
}
