// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/get-profile-deletion-status.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileDeletionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profileId,proto3" json:"profileId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileDeletionStatusRequest) Reset() {
	*x = GetProfileDeletionStatusRequest{}
	mi := &file_v1_get_profile_deletion_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileDeletionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileDeletionStatusRequest) ProtoMessage() {}

func (x *GetProfileDeletionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_profile_deletion_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileDeletionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetProfileDeletionStatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_profile_deletion_status_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileDeletionStatusRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type GetProfileDeletionStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeletionTimestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deletionTimestamp,proto3" json:"deletionTimestamp,omitempty"`
	Deleted           bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProfileDeletionStatusResponse) Reset() {
	*x = GetProfileDeletionStatusResponse{}
	mi := &file_v1_get_profile_deletion_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileDeletionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileDeletionStatusResponse) ProtoMessage() {}

func (x *GetProfileDeletionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_profile_deletion_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileDeletionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetProfileDeletionStatusResponse) Descriptor() ([]byte, []int) {
	return file_v1_get_profile_deletion_status_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileDeletionStatusResponse) GetDeletionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTimestamp
	}
	return nil
}

func (x *GetProfileDeletionStatusResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_v1_get_profile_deletion_status_proto protoreflect.FileDescriptor

const file_v1_get_profile_deletion_status_proto_rawDesc = "" +
	"\n" +
	"$v1/get-profile-deletion-status.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"?\n" +
	"\x1fGetProfileDeletionStatusRequest\x12\x1c\n" +
	"\tprofileId\x18\x01 \x01(\tR\tprofileId\"\x86\x01\n" +
	" GetProfileDeletionStatusResponse\x12H\n" +
	"\x11deletionTimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x11deletionTimestamp\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeletedB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_get_profile_deletion_status_proto_rawDescOnce sync.Once
	file_v1_get_profile_deletion_status_proto_rawDescData []byte
)

func file_v1_get_profile_deletion_status_proto_rawDescGZIP() []byte {
	file_v1_get_profile_deletion_status_proto_rawDescOnce.Do(func() {
		file_v1_get_profile_deletion_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_get_profile_deletion_status_proto_rawDesc), len(file_v1_get_profile_deletion_status_proto_rawDesc)))
	})
	return file_v1_get_profile_deletion_status_proto_rawDescData
}

var file_v1_get_profile_deletion_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_get_profile_deletion_status_proto_goTypes = []any{
	(*GetProfileDeletionStatusRequest)(nil),  // 0: v1.GetProfileDeletionStatusRequest
	(*GetProfileDeletionStatusResponse)(nil), // 1: v1.GetProfileDeletionStatusResponse
	(*timestamppb.Timestamp)(nil),            // 2: google.protobuf.Timestamp
}
var file_v1_get_profile_deletion_status_proto_depIdxs = []int32{
	2, // 0: v1.GetProfileDeletionStatusResponse.deletionTimestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_get_profile_deletion_status_proto_init() }
func file_v1_get_profile_deletion_status_proto_init() {
	if File_v1_get_profile_deletion_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_get_profile_deletion_status_proto_rawDesc), len(file_v1_get_profile_deletion_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_get_profile_deletion_status_proto_goTypes,
		DependencyIndexes: file_v1_get_profile_deletion_status_proto_depIdxs,
		MessageInfos:      file_v1_get_profile_deletion_status_proto_msgTypes,
	}.Build()
	File_v1_get_profile_deletion_status_proto = out.File
	file_v1_get_profile_deletion_status_proto_goTypes = nil
	file_v1_get_profile_deletion_status_proto_depIdxs = nil
}
