// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/get-access-token-public-key.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccessTokenPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenPublicKeyRequest) Reset() {
	*x = GetAccessTokenPublicKeyRequest{}
	mi := &file_v1_get_access_token_public_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenPublicKeyRequest) ProtoMessage() {}

func (x *GetAccessTokenPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_access_token_public_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAccessTokenPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_access_token_public_key_proto_rawDescGZIP(), []int{0}
}

type GetAccessTokenPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenPublicKeyResponse) Reset() {
	*x = GetAccessTokenPublicKeyResponse{}
	mi := &file_v1_get_access_token_public_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenPublicKeyResponse) ProtoMessage() {}

func (x *GetAccessTokenPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_access_token_public_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAccessTokenPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_v1_get_access_token_public_key_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccessTokenPublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_v1_get_access_token_public_key_proto protoreflect.FileDescriptor

const file_v1_get_access_token_public_key_proto_rawDesc = "" +
	"\n" +
	"$v1/get-access-token-public-key.proto\x12\x02v1\" \n" +
	"\x1eGetAccessTokenPublicKeyRequest\"?\n" +
	"\x1fGetAccessTokenPublicKeyResponse\x12\x1c\n" +
	"\tpublicKey\x18\x01 \x01(\fR\tpublicKeyB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_get_access_token_public_key_proto_rawDescOnce sync.Once
	file_v1_get_access_token_public_key_proto_rawDescData []byte
)

func file_v1_get_access_token_public_key_proto_rawDescGZIP() []byte {
	file_v1_get_access_token_public_key_proto_rawDescOnce.Do(func() {
		file_v1_get_access_token_public_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_get_access_token_public_key_proto_rawDesc), len(file_v1_get_access_token_public_key_proto_rawDesc)))
	})
	return file_v1_get_access_token_public_key_proto_rawDescData
}

var file_v1_get_access_token_public_key_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_get_access_token_public_key_proto_goTypes = []any{
	(*GetAccessTokenPublicKeyRequest)(nil),  // 0: v1.GetAccessTokenPublicKeyRequest
	(*GetAccessTokenPublicKeyResponse)(nil), // 1: v1.GetAccessTokenPublicKeyResponse
}
var file_v1_get_access_token_public_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_get_access_token_public_key_proto_init() }
func file_v1_get_access_token_public_key_proto_init() {
	if File_v1_get_access_token_public_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_get_access_token_public_key_proto_rawDesc), len(file_v1_get_access_token_public_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_get_access_token_public_key_proto_goTypes,
		DependencyIndexes: file_v1_get_access_token_public_key_proto_depIdxs,
		MessageInfos:      file_v1_get_access_token_public_key_proto_msgTypes,
	}.Build()
	File_v1_get_access_token_public_key_proto = out.File
	file_v1_get_access_token_public_key_proto_goTypes = nil
	file_v1_get_access_token_public_key_proto_depIdxs = nil
}
