// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/get-sessions.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsRequest) Reset() {
	*x = GetSessionsRequest{}
	mi := &file_v1_get_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsRequest) ProtoMessage() {}

func (x *GetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsResponse) Reset() {
	*x = GetSessionsResponse{}
	mi := &file_v1_get_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsResponse) ProtoMessage() {}

func (x *GetSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_get_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	AccessPoint   string                 `protobuf:"bytes,3,opt,name=accessPoint,proto3" json:"accessPoint,omitempty"`
	Mobile        bool                   `protobuf:"varint,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AccessTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=accessTime,proto3" json:"accessTime,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_v1_get_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_v1_get_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Session) GetAccessPoint() string {
	if x != nil {
		return x.AccessPoint
	}
	return ""
}

func (x *Session) GetMobile() bool {
	if x != nil {
		return x.Mobile
	}
	return false
}

func (x *Session) GetAccessTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTime
	}
	return nil
}

func (x *Session) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_v1_get_sessions_proto protoreflect.FileDescriptor

const file_v1_get_sessions_proto_rawDesc = "" +
	"\n" +
	"\x15v1/get-sessions.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\x12GetSessionsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x13GetSessionsResponse\x12'\n" +
	"\bsessions\x18\x01 \x03(\v2\v.v1.SessionR\bsessions\"\xbb\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12 \n" +
	"\vaccessPoint\x18\x03 \x01(\tR\vaccessPoint\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\bR\x06mobile\x12:\n" +
	"\n" +
	"accessTime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"accessTime\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocationB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_get_sessions_proto_rawDescOnce sync.Once
	file_v1_get_sessions_proto_rawDescData []byte
)

func file_v1_get_sessions_proto_rawDescGZIP() []byte {
	file_v1_get_sessions_proto_rawDescOnce.Do(func() {
		file_v1_get_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_get_sessions_proto_rawDesc), len(file_v1_get_sessions_proto_rawDesc)))
	})
	return file_v1_get_sessions_proto_rawDescData
}

var file_v1_get_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_get_sessions_proto_goTypes = []any{
	(*GetSessionsRequest)(nil),    // 0: v1.GetSessionsRequest
	(*GetSessionsResponse)(nil),   // 1: v1.GetSessionsResponse
	(*Session)(nil),               // 2: v1.Session
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_get_sessions_proto_depIdxs = []int32{
	2, // 0: v1.GetSessionsResponse.sessions:type_name -> v1.Session
	3, // 1: v1.Session.accessTime:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_get_sessions_proto_init() }
func file_v1_get_sessions_proto_init() {
	if File_v1_get_sessions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_get_sessions_proto_rawDesc), len(file_v1_get_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_get_sessions_proto_goTypes,
		DependencyIndexes: file_v1_get_sessions_proto_depIdxs,
		MessageInfos:      file_v1_get_sessions_proto_msgTypes,
	}.Build()
	File_v1_get_sessions_proto = out.File
	file_v1_get_sessions_proto_goTypes = nil
	file_v1_get_sessions_proto_depIdxs = nil
}
