// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/get-auth-info.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAuthInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthInfoRequest) Reset() {
	*x = GetAuthInfoRequest{}
	mi := &file_v1_get_auth_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthInfoRequest) ProtoMessage() {}

func (x *GetAuthInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_auth_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAuthInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_auth_info_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuthInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAuthInfoRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetAuthInfoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetAuthInfoResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                 string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username              *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Role                  string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	RegistrationTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=registrationTimestamp,proto3" json:"registrationTimestamp,omitempty"`
	IsActivated           bool                   `protobuf:"varint,6,opt,name=isActivated,proto3" json:"isActivated,omitempty"`
	IsBlocked             bool                   `protobuf:"varint,7,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	OAuth                 *OAuth                 `protobuf:"bytes,8,opt,name=oAuth,proto3" json:"oAuth,omitempty"`
	DeletionTimestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deletionTimestamp,proto3" json:"deletionTimestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetAuthInfoResponse) Reset() {
	*x = GetAuthInfoResponse{}
	mi := &file_v1_get_auth_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthInfoResponse) ProtoMessage() {}

func (x *GetAuthInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_auth_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAuthInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_get_auth_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthInfoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAuthInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetAuthInfoResponse) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *GetAuthInfoResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetAuthInfoResponse) GetRegistrationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationTimestamp
	}
	return nil
}

func (x *GetAuthInfoResponse) GetIsActivated() bool {
	if x != nil {
		return x.IsActivated
	}
	return false
}

func (x *GetAuthInfoResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *GetAuthInfoResponse) GetOAuth() *OAuth {
	if x != nil {
		return x.OAuth
	}
	return nil
}

func (x *GetAuthInfoResponse) GetDeletionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTimestamp
	}
	return nil
}

type OAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoogleId      *string                `protobuf:"bytes,1,opt,name=googleId,proto3,oneof" json:"googleId,omitempty"`
	VkId          *int64                 `protobuf:"varint,2,opt,name=vkId,proto3,oneof" json:"vkId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth) Reset() {
	*x = OAuth{}
	mi := &file_v1_get_auth_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth) ProtoMessage() {}

func (x *OAuth) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_auth_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth.ProtoReflect.Descriptor instead.
func (*OAuth) Descriptor() ([]byte, []int) {
	return file_v1_get_auth_info_proto_rawDescGZIP(), []int{2}
}

func (x *OAuth) GetGoogleId() string {
	if x != nil && x.GoogleId != nil {
		return *x.GoogleId
	}
	return ""
}

func (x *OAuth) GetVkId() int64 {
	if x != nil && x.VkId != nil {
		return *x.VkId
	}
	return 0
}

var File_v1_get_auth_info_proto protoreflect.FileDescriptor

const file_v1_get_auth_info_proto_rawDesc = "" +
	"\n" +
	"\x16v1/get-auth-info.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\x12GetAuthInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"\xfa\x02\n" +
	"\x13GetAuthInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x00R\busername\x88\x01\x01\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12P\n" +
	"\x15registrationTimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x15registrationTimestamp\x12 \n" +
	"\visActivated\x18\x06 \x01(\bR\visActivated\x12\x1c\n" +
	"\tisBlocked\x18\a \x01(\bR\tisBlocked\x12\x1f\n" +
	"\x05oAuth\x18\b \x01(\v2\t.v1.OAuthR\x05oAuth\x12H\n" +
	"\x11deletionTimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x11deletionTimestampB\v\n" +
	"\t_username\"W\n" +
	"\x05OAuth\x12\x1f\n" +
	"\bgoogleId\x18\x01 \x01(\tH\x00R\bgoogleId\x88\x01\x01\x12\x17\n" +
	"\x04vkId\x18\x02 \x01(\x03H\x01R\x04vkId\x88\x01\x01B\v\n" +
	"\t_googleIdB\a\n" +
	"\x05_vkIdB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_get_auth_info_proto_rawDescOnce sync.Once
	file_v1_get_auth_info_proto_rawDescData []byte
)

func file_v1_get_auth_info_proto_rawDescGZIP() []byte {
	file_v1_get_auth_info_proto_rawDescOnce.Do(func() {
		file_v1_get_auth_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_get_auth_info_proto_rawDesc), len(file_v1_get_auth_info_proto_rawDesc)))
	})
	return file_v1_get_auth_info_proto_rawDescData
}

var file_v1_get_auth_info_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_get_auth_info_proto_goTypes = []any{
	(*GetAuthInfoRequest)(nil),    // 0: v1.GetAuthInfoRequest
	(*GetAuthInfoResponse)(nil),   // 1: v1.GetAuthInfoResponse
	(*OAuth)(nil),                 // 2: v1.OAuth
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_get_auth_info_proto_depIdxs = []int32{
	3, // 0: v1.GetAuthInfoResponse.registrationTimestamp:type_name -> google.protobuf.Timestamp
	2, // 1: v1.GetAuthInfoResponse.oAuth:type_name -> v1.OAuth
	3, // 2: v1.GetAuthInfoResponse.deletionTimestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_get_auth_info_proto_init() }
func file_v1_get_auth_info_proto_init() {
	if File_v1_get_auth_info_proto != nil {
		return
	}
	file_v1_get_auth_info_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_get_auth_info_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_get_auth_info_proto_rawDesc), len(file_v1_get_auth_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_get_auth_info_proto_goTypes,
		DependencyIndexes: file_v1_get_auth_info_proto_depIdxs,
		MessageInfos:      file_v1_get_auth_info_proto_msgTypes,
	}.Build()
	File_v1_get_auth_info_proto = out.File
	file_v1_get_auth_info_proto_goTypes = nil
	file_v1_get_auth_info_proto_depIdxs = nil
}
