// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/request-google-oauth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestGoogleOAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowBinding   string                 `protobuf:"bytes,20,opt,name=flowBinding,proto3" json:"flowBinding,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,1,opt,name=redirectUrl,proto3" json:"redirectUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGoogleOAuthRequest) Reset() {
	*x = RequestGoogleOAuthRequest{}
	mi := &file_v1_request_google_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGoogleOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGoogleOAuthRequest) ProtoMessage() {}

func (x *RequestGoogleOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_request_google_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGoogleOAuthRequest.ProtoReflect.Descriptor instead.
func (*RequestGoogleOAuthRequest) Descriptor() ([]byte, []int) {
	return file_v1_request_google_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGoogleOAuthRequest) GetFlowBinding() string {
	if x != nil {
		return x.FlowBinding
	}
	return ""
}

func (x *RequestGoogleOAuthRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type RequestGoogleOAuthResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Link                string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	ExpirationTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expirationTimestamp,proto3" json:"expirationTimestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RequestGoogleOAuthResponse) Reset() {
	*x = RequestGoogleOAuthResponse{}
	mi := &file_v1_request_google_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGoogleOAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGoogleOAuthResponse) ProtoMessage() {}

func (x *RequestGoogleOAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_request_google_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGoogleOAuthResponse.ProtoReflect.Descriptor instead.
func (*RequestGoogleOAuthResponse) Descriptor() ([]byte, []int) {
	return file_v1_request_google_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *RequestGoogleOAuthResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RequestGoogleOAuthResponse) GetExpirationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationTimestamp
	}
	return nil
}

var File_v1_request_google_oauth_proto protoreflect.FileDescriptor

const file_v1_request_google_oauth_proto_rawDesc = "" +
	"\n" +
	"\x1dv1/request-google-oauth.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\x19RequestGoogleOAuthRequest\x12 \n" +
	"\vflowBinding\x18\x14 \x01(\tR\vflowBinding\x12 \n" +
	"\vredirectUrl\x18\x01 \x01(\tR\vredirectUrl\"~\n" +
	"\x1aRequestGoogleOAuthResponse\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12L\n" +
	"\x13expirationTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x13expirationTimestampB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_request_google_oauth_proto_rawDescOnce sync.Once
	file_v1_request_google_oauth_proto_rawDescData []byte
)

func file_v1_request_google_oauth_proto_rawDescGZIP() []byte {
	file_v1_request_google_oauth_proto_rawDescOnce.Do(func() {
		file_v1_request_google_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_request_google_oauth_proto_rawDesc), len(file_v1_request_google_oauth_proto_rawDesc)))
	})
	return file_v1_request_google_oauth_proto_rawDescData
}

var file_v1_request_google_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_request_google_oauth_proto_goTypes = []any{
	(*RequestGoogleOAuthRequest)(nil),  // 0: v1.RequestGoogleOAuthRequest
	(*RequestGoogleOAuthResponse)(nil), // 1: v1.RequestGoogleOAuthResponse
	(*timestamppb.Timestamp)(nil),      // 2: google.protobuf.Timestamp
}
var file_v1_request_google_oauth_proto_depIdxs = []int32{
	2, // 0: v1.RequestGoogleOAuthResponse.expirationTimestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_request_google_oauth_proto_init() }
func file_v1_request_google_oauth_proto_init() {
	if File_v1_request_google_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_request_google_oauth_proto_rawDesc), len(file_v1_request_google_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_request_google_oauth_proto_goTypes,
		DependencyIndexes: file_v1_request_google_oauth_proto_depIdxs,
		MessageInfos:      file_v1_request_google_oauth_proto_msgTypes,
	}.Build()
	File_v1_request_google_oauth_proto = out.File
	file_v1_request_google_oauth_proto_goTypes = nil
	file_v1_request_google_oauth_proto_depIdxs = nil
}
