// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/request-password-reset.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestPasswordResetRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Email                    string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username                 string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ResetPasswordLinkPattern string                 `protobuf:"bytes,4,opt,name=resetPasswordLinkPattern,proto3" json:"resetPasswordLinkPattern,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RequestPasswordResetRequest) Reset() {
	*x = RequestPasswordResetRequest{}
	mi := &file_v1_request_password_reset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetRequest) ProtoMessage() {}

func (x *RequestPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_request_password_reset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_v1_request_password_reset_proto_rawDescGZIP(), []int{0}
}

func (x *RequestPasswordResetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RequestPasswordResetRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RequestPasswordResetRequest) GetResetPasswordLinkPattern() string {
	if x != nil {
		return x.ResetPasswordLinkPattern
	}
	return ""
}

type RequestPasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordResetResponse) Reset() {
	*x = RequestPasswordResetResponse{}
	mi := &file_v1_request_password_reset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetResponse) ProtoMessage() {}

func (x *RequestPasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_request_password_reset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetResponse.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_v1_request_password_reset_proto_rawDescGZIP(), []int{1}
}

func (x *RequestPasswordResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_request_password_reset_proto protoreflect.FileDescriptor

const file_v1_request_password_reset_proto_rawDesc = "" +
	"\n" +
	"\x1fv1/request-password-reset.proto\x12\x02v1\"\x8b\x01\n" +
	"\x1bRequestPasswordResetRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12:\n" +
	"\x18resetPasswordLinkPattern\x18\x04 \x01(\tR\x18resetPasswordLinkPattern\"8\n" +
	"\x1cRequestPasswordResetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_request_password_reset_proto_rawDescOnce sync.Once
	file_v1_request_password_reset_proto_rawDescData []byte
)

func file_v1_request_password_reset_proto_rawDescGZIP() []byte {
	file_v1_request_password_reset_proto_rawDescOnce.Do(func() {
		file_v1_request_password_reset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_request_password_reset_proto_rawDesc), len(file_v1_request_password_reset_proto_rawDesc)))
	})
	return file_v1_request_password_reset_proto_rawDescData
}

var file_v1_request_password_reset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_request_password_reset_proto_goTypes = []any{
	(*RequestPasswordResetRequest)(nil),  // 0: v1.RequestPasswordResetRequest
	(*RequestPasswordResetResponse)(nil), // 1: v1.RequestPasswordResetResponse
}
var file_v1_request_password_reset_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_request_password_reset_proto_init() }
func file_v1_request_password_reset_proto_init() {
	if File_v1_request_password_reset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_request_password_reset_proto_rawDesc), len(file_v1_request_password_reset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_request_password_reset_proto_goTypes,
		DependencyIndexes: file_v1_request_password_reset_proto_depIdxs,
		MessageInfos:      file_v1_request_password_reset_proto_msgTypes,
	}.Build()
	File_v1_request_password_reset_proto = out.File
	file_v1_request_password_reset_proto_goTypes = nil
	file_v1_request_password_reset_proto_depIdxs = nil
}
