// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/session.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ProfileId                string                 `protobuf:"bytes,1,opt,name=profileId,proto3" json:"profileId,omitempty"`
	AccessToken              string                 `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken             string                 `protobuf:"bytes,3,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	ExpirationTimestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expirationTimestamp,proto3" json:"expirationTimestamp,omitempty"`
	ProfileDeletionTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=profileDeletionTimestamp,proto3" json:"profileDeletionTimestamp,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *SessionResponse) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *SessionResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SessionResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *SessionResponse) GetExpirationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationTimestamp
	}
	return nil
}

func (x *SessionResponse) GetProfileDeletionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ProfileDeletionTimestamp
	}
	return nil
}

var File_v1_session_proto protoreflect.FileDescriptor

const file_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x10v1/session.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x02\n" +
	"\x0fSessionResponse\x12\x1c\n" +
	"\tprofileId\x18\x01 \x01(\tR\tprofileId\x12 \n" +
	"\vaccessToken\x18\x02 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x03 \x01(\tR\frefreshToken\x12L\n" +
	"\x13expirationTimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x13expirationTimestamp\x12V\n" +
	"\x18profileDeletionTimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x18profileDeletionTimestampB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_session_proto_rawDescOnce sync.Once
	file_v1_session_proto_rawDescData []byte
)

func file_v1_session_proto_rawDescGZIP() []byte {
	file_v1_session_proto_rawDescOnce.Do(func() {
		file_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_session_proto_rawDesc), len(file_v1_session_proto_rawDesc)))
	})
	return file_v1_session_proto_rawDescData
}

var file_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_session_proto_goTypes = []any{
	(*SessionResponse)(nil),       // 0: v1.SessionResponse
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_v1_session_proto_depIdxs = []int32{
	1, // 0: v1.SessionResponse.expirationTimestamp:type_name -> google.protobuf.Timestamp
	1, // 1: v1.SessionResponse.profileDeletionTimestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_session_proto_init() }
func file_v1_session_proto_init() {
	if File_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_session_proto_rawDesc), len(file_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_session_proto_goTypes,
		DependencyIndexes: file_v1_session_proto_depIdxs,
		MessageInfos:      file_v1_session_proto_msgTypes,
	}.Build()
	File_v1_session_proto = out.File
	file_v1_session_proto_goTypes = nil
	file_v1_session_proto_depIdxs = nil
}
