// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/sign-in-google-token.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignInGoogleTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInGoogleTokenRequest) Reset() {
	*x = SignInGoogleTokenRequest{}
	mi := &file_v1_sign_in_google_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInGoogleTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInGoogleTokenRequest) ProtoMessage() {}

func (x *SignInGoogleTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sign_in_google_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInGoogleTokenRequest.ProtoReflect.Descriptor instead.
func (*SignInGoogleTokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_sign_in_google_token_proto_rawDescGZIP(), []int{0}
}

func (x *SignInGoogleTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SignInGoogleTokenRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SignInGoogleTokenRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

var File_v1_sign_in_google_token_proto protoreflect.FileDescriptor

const file_v1_sign_in_google_token_proto_rawDesc = "" +
	"\n" +
	"\x1dv1/sign-in-google-token.proto\x12\x02v1\"^\n" +
	"\x18SignInGoogleTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1c\n" +
	"\tuserAgent\x18\x03 \x01(\tR\tuserAgentB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_sign_in_google_token_proto_rawDescOnce sync.Once
	file_v1_sign_in_google_token_proto_rawDescData []byte
)

func file_v1_sign_in_google_token_proto_rawDescGZIP() []byte {
	file_v1_sign_in_google_token_proto_rawDescOnce.Do(func() {
		file_v1_sign_in_google_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_sign_in_google_token_proto_rawDesc), len(file_v1_sign_in_google_token_proto_rawDesc)))
	})
	return file_v1_sign_in_google_token_proto_rawDescData
}

var file_v1_sign_in_google_token_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_sign_in_google_token_proto_goTypes = []any{
	(*SignInGoogleTokenRequest)(nil), // 0: v1.SignInGoogleTokenRequest
}
var file_v1_sign_in_google_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_sign_in_google_token_proto_init() }
func file_v1_sign_in_google_token_proto_init() {
	if File_v1_sign_in_google_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_sign_in_google_token_proto_rawDesc), len(file_v1_sign_in_google_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_sign_in_google_token_proto_goTypes,
		DependencyIndexes: file_v1_sign_in_google_token_proto_depIdxs,
		MessageInfos:      file_v1_sign_in_google_token_proto_msgTypes,
	}.Build()
	File_v1_sign_in_google_token_proto = out.File
	file_v1_sign_in_google_token_proto_goTypes = nil
	file_v1_sign_in_google_token_proto_depIdxs = nil
}
