// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: v1/sign-out.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutRequest) Reset() {
	*x = SignOutRequest{}
	mi := &file_v1_sign_out_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutRequest) ProtoMessage() {}

func (x *SignOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sign_out_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutRequest.ProtoReflect.Descriptor instead.
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return file_v1_sign_out_proto_rawDescGZIP(), []int{0}
}

func (x *SignOutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type SignOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutResponse) Reset() {
	*x = SignOutResponse{}
	mi := &file_v1_sign_out_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutResponse) ProtoMessage() {}

func (x *SignOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sign_out_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutResponse.ProtoReflect.Descriptor instead.
func (*SignOutResponse) Descriptor() ([]byte, []int) {
	return file_v1_sign_out_proto_rawDescGZIP(), []int{1}
}

func (x *SignOutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_sign_out_proto protoreflect.FileDescriptor

const file_v1_sign_out_proto_rawDesc = "" +
	"\n" +
	"\x11v1/sign-out.proto\x12\x02v1\"4\n" +
	"\x0eSignOutRequest\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"+\n" +
	"\x0fSignOutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB;Z9github.com/mephistolie/chefbook-backend-auth/api/proto/v1b\x06proto3"

var (
	file_v1_sign_out_proto_rawDescOnce sync.Once
	file_v1_sign_out_proto_rawDescData []byte
)

func file_v1_sign_out_proto_rawDescGZIP() []byte {
	file_v1_sign_out_proto_rawDescOnce.Do(func() {
		file_v1_sign_out_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_sign_out_proto_rawDesc), len(file_v1_sign_out_proto_rawDesc)))
	})
	return file_v1_sign_out_proto_rawDescData
}

var file_v1_sign_out_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_sign_out_proto_goTypes = []any{
	(*SignOutRequest)(nil),  // 0: v1.SignOutRequest
	(*SignOutResponse)(nil), // 1: v1.SignOutResponse
}
var file_v1_sign_out_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_sign_out_proto_init() }
func file_v1_sign_out_proto_init() {
	if File_v1_sign_out_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_sign_out_proto_rawDesc), len(file_v1_sign_out_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_sign_out_proto_goTypes,
		DependencyIndexes: file_v1_sign_out_proto_depIdxs,
		MessageInfos:      file_v1_sign_out_proto_msgTypes,
	}.Build()
	File_v1_sign_out_proto = out.File
	file_v1_sign_out_proto_goTypes = nil
	file_v1_sign_out_proto_depIdxs = nil
}
